### ISSUE TITLE
PAT Scope

### ISSUE THREAD

**Issue by Amaranthos** [MicrosoftDocs/vsts-rest-api-specs#101]
It would be good to know which scopes are required to interact with each section of the api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31074e0d-62b1-31cf-8d16-f957cfb750f9
* Version Independent ID: 1cff91ee-df5a-8828-a658-b8c7b47eb361
* Content: [Repositories (VSTS Git)](https://docs.microsoft.com/en-us/rest/api/vsts/git/repositories?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/git/Repositories.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/git/Repositories.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
@Amaranthos thanks for reporting this. Agreed, this is something we'd like to support. Keeping this open for tracking and adding this item to the backlog.

**Comment by wnjenkin** [comment]
@Amaranthos We've added this information to our API's. Let me know if you have any additional feedback.
