### ISSUE TITLE
"Git blobs" link is dead.

### ISSUE THREAD

**Issue by IOrlandoni** [MicrosoftDocs/vsts-rest-api-specs#102]
"Git blobs" link is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: 34a63078-bfe5-7cb5-e278-bf9edaa3fa4d
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by wnjenkin** [comment]
@IOrlandoni thanks for reporting. We've resolved this issue. Please let us know if you are still experiencing any issues
