### ISSUE TITLE
Feature Request: Deploy specific stage in a release

### ISSUE THREAD

**Issue by tilumi** [MicrosoftDocs/vsts-rest-api-specs#104]
We have a requirement to restart service, but we don't want making config & code duplicated where one is in Azure DevOps settings and another is write a script to restart a server.
For example, we have a release pipeline like this:
![screenshot 2018-10-06 07 25 55](https://user-images.githubusercontent.com/734766/46564327-296b0b00-c939-11e8-8116-723546979de7.png)
The ideal process is
1. Create a release with "Stages for a trigger change from automated to manual." set to initial stages to block auto release through API call.
2. Deploy a specific stage through API call.
3. Abandon the release through API call

**Comment by wnjenkin** [comment]
@tilumi thanks for filing this feature request. I would suggest transferring this request to https://developercommunity.visualstudio.com/spaces/21/index.html .

**Comment by pulkitaggarwl** [comment]
+ @shashban 
Did you get a chance to look at our APIs for this one?

You would be able to update each stage.  Refer: https://docs.microsoft.com/en-us/rest/api/vsts/release/releases/update%20release%20environment?view=vsts-rest-4.1

For modifying release you can use : https://docs.microsoft.com/en-us/rest/api/vsts/release/releases/update%20release?view=vsts-rest-4.1
