### ISSUE TITLE
You don't list necessary scope permissions to perform API actions

### ISSUE THREAD

**Issue by charlespaske** [MicrosoftDocs/vsts-rest-api-specs#109]
I'm trying to use a PAT to authentication an application that is using the REST API but in order to perform a DELETE I have to use a token with "All Scopes" selected.  To create policy configurations it looks like having "Code (Full)" is enough but even if I manually select every scope, none of them give permissions to delete a policy configuration.  Only selecting "All Scopes" does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d635175e-8ab5-dd18-2b4a-18587075cab6
* Version Independent ID: dffee946-f65f-2b4c-bacf-0e42f3392398
* Content: [Configurations (VSTS Policy)](https://docs.microsoft.com/en-us/rest/api/vsts/policy/configurations?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/policy/Configurations.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/policy/Configurations.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
@charlespaske thanks for providing this feedback. We're tracking this request via this issue #101

**Comment by wnjenkin** [comment]
@charlespaske if you'd like to get unblocked immediately, you can find the permissions needed to perform an action directly in the swagger file - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/policy/4.1/policy.json

**Comment by charlespaske** [comment]
It looks like for DELETE it's missing the security section in the swagger file:
```json
"delete": {
        "tags": [
          "Configurations"
        ],
        "x-ms-docs-override-version": "4.1",
        "x-ms-vss-resource": "configurations",
        "x-ms-vss-method": "DeletePolicyConfiguration",
        "description": "Delete a policy configuration by its ID.",
        "operationId": "Delete",
        "parameters": [
          {
            "in": "path",
            "name": "organization",
            "description": "The name of the Azure DevOps organization.",
            "required": true,
            "type": "string"
          },
          {
            "in": "path",
            "name": "project",
            "description": "Project ID or project name",
            "required": true,
            "type": "string"
          },
          {
            "in": "path",
            "name": "configurationId",
            "description": "ID of the policy configuration to delete.",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "$ref": "#/parameters/api-Version"
          }
        ],
        "responses": {
          "204": {
            "description": "NoContent"
          }
        },
        "x-ms-examples": {
          "": {
            "$ref": "./httpExamples/Configurations/DELETE__policy_configurations__configurationId_.json"
          }
        }
      }
```
That's what is currently blocking me is which scope is needed for delete.

**Comment by wnjenkin** [comment]
@charlespaske closing this issue since oauth scope has been added to our apis. Let me know if you're still experiencing issues.
