### ISSUE TITLE
Ticket provider details

### ISSUE THREAD

**Issue by ParidaPunyasloka** [MicrosoftDocs/vsts-rest-api-specs#111]
How do I find the ticket provider? what is the value for the ticket provider? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a40a32-5390-438c-3d3f-3f75dc9e6ce4
* Version Independent ID: 91b699df-3081-69ee-12c0-11f652ea44f7
* Content: [Ticketed Logs (VSTS Build)](https://docs.microsoft.com/en-us/rest/api/vsts/build/ticketed%20logs?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/build/Ticketed%20Logs.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/build/Ticketed%20Logs.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by chrisrpatterson** [comment]
This is an API surface that should not have been documented.  We will make sure it is pulled from the docs.
