### ISSUE TITLE
Repeated entries in the API overview pages

### ISSUE THREAD

**Issue by jackhorton** [MicrosoftDocs/vsts-rest-api-specs#113]
In a page like https://docs.microsoft.com/en-us/rest/api/vsts/policy/evaluations?view=vsts-rest-5.0, every "Operation" is duplicated. As far as I can tell, every operation list page in the docs is like this.

![image](https://user-images.githubusercontent.com/4370013/47868586-c6e31e80-ddc1-11e8-9919-7e84f96baa0d.png)

**Comment by wnjenkin** [comment]
@jackhorton thanks for reporting this issue. We have a fix and it will be deployed shortly

**Comment by wnjenkin** [comment]
This has been resolved
