### ISSUE TITLE
The operations are duplicated on this page. 

### ISSUE THREAD

**Issue by brandonmcclure** [MicrosoftDocs/vsts-rest-api-specs#119]
In the navigation pane to the left, each operation is listed once. On the documentation page, each operation is listed twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ebd27b9-b8ef-10fc-db9f-70026eeb27dc
* Version Independent ID: 082f3ffd-2c0e-9fdc-d52d-758de05a9557
* Content: [Work Items (VSTS Work Item Tracking)](https://docs.microsoft.com/en-us/rest/api/vsts/wit/work%20items?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/wit/Work%20Items.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/wit/Work%20Items.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
@brandonmcclure we've got a fix for this issue ready in the next update. thanks for reporting

**Comment by wnjenkin** [comment]
This has been resolved
