### ISSUE TITLE
Duplicate Operations in Code Search Results

### ISSUE THREAD

**Issue by rjmholt** [MicrosoftDocs/vsts-rest-api-specs#120]
There are two `Operations` listed on the Code Search Results page, but they are the same name, link and description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5dfe68b-6441-a2ff-4a79-67ef082290b9
* Version Independent ID: b59ce0be-b7de-6a5d-ed86-c2bfce8f5c56
* Content: [Code Search Results (VSTS Search)](https://docs.microsoft.com/en-us/rest/api/vsts/search/code%20search%20results?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/search/Code%20Search%20Results.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/search/Code%20Search%20Results.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
This has been resolved
