### ISSUE TITLE
Error Handling: Case where single request in batch api fails

### ISSUE THREAD

**Issue by IdiotLeon** [MicrosoftDocs/vsts-rest-api-specs#121]
Assume a scenario: there is a batch request for 100 work items, 3 of them fail, while 97 succeed:
The 97 successful updates will be performed, correct?
Will the successes messages be included in the HTTP response? 
If no, how to know which ones fail?
If yes, how to know which ones fail?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636cee4f-faf7-0087-57df-94db6dde64c7
* Version Independent ID: a2a62f06-2d91-191f-72a8-282c1cd93564
* Content: [| Microsoft Docs](https://docs.microsoft.com/en-us/rest/api/vsts/wit/WorkItemBatchUpdate?view=vsts-rest-4.1)
* Content Source: [docs-ref-conceptual/4.1/wit/WorkItemBatchUpdate.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/4.1/wit/WorkItemBatchUpdate.md)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
@danhellem to help out

**Comment by danhellem** [comment]
Assume a scenario: there is a batch request for 100 work items, 3 of them fail, while 97 succeed:
The 97 successful updates will be performed, correct?
_No, it is an all or nothing scenario. If one fails nothing with be updated._

Will the successes messages be included in the HTTP response?
If no, how to know which ones fail?
_The failed items are part of the failed response. here is an example of what to expect._

Request Url : https://codedev.ms/sample/_apis/wit/$batch
Request Body : 
[{
            "method": "PATCH",
            "uri": "/_apis/wit/workitems/1?api-version=1.0",
            "headers": {
                        "Content-Type": "application/json-patch+json"
            },
            "body": [{
                        "op": "add",
                        "path": "/relations/-",
                        "value": {
                                    "rel": "Hyperlink",
                                    "url": "http://blogs.msdn.com/b/bharry/archive/2014/05/12/a-new-api-for-visual-studio-online.aspx"
                        }
                        },
                        {
                                    "op": "add",
                                    "path": "/relations/-",
                                    "value": {
                                                "rel": "Hyperlink",
                                                "url": "https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1"
                                    }
                        }
            ]
            },
            {
                        "method": "PATCH",
                        "uri": "/_apis/wit/workitems/2?api-version=1.0",
                        "headers": {
                                    "Content-Type": "application/json-patch+json"
                        },
                        "body": [{
                                    "op": "add",
                                    "path": "/relatioddns/-", This will cause failure… 
                                    "value": {
                                                "rel": "Hyperlink",
                                                "url": "https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1"
                                    }
                                    },
                                    {
                                                "op": "add",
                                                "path": "/relations/-",
                                                "value": {
                                                            "rel": "Hyperlink",
                                                            "url": "http://blogs.msdn.com/b/bharry/archive/2014/05/12/a-new-api-for-visual-studio-online.aspx"
                                                }
                                    }
                        ]
            }
]

Response : 
{
    "count": 1,
    "value": [
        {
            "code": 400,
            "headers": {
                "Content-Type": "application/json; charset=utf-8"
            },
            "body": "{\"count\":1,\"value\":{\"Message\":\"Unable to evaluate path /relatioddns/-.\"}}"
        }
    ]
}
