### ISSUE TITLE
Set autocomplete via REST Api example doesn't work

### ISSUE THREAD

**Issue by andreasblueher** [MicrosoftDocs/vsts-rest-api-specs#134]
Hey,

I've followed [those instructions](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests/update?view=azure-devops-rest-4.1#enable_auto-completion_and_set_other_completion_options) but I'm not getting the expected results.

In the example after sending the body to the endpoint the response shows "setAutocompleteBy" being set for the given userId, but in my case this section is missing my response. I do get back the compeltionOptions I've set, but they're also not set in the pull request correctly.

Is there a way I can send you more detailled information (request bodies, responses), without shareing those information here on GitHub. Don't feel comfortable publishing our urls, userids and so forth.

Cheers Andreas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b27ca2-d849-e571-931b-95c351de12fc
* Version Independent ID: 7b98c04a-c934-a4a9-4f57-55bd0afccf76
* Content: [Pull Requests (VSTS Git)](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests?view=azure-devops-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/git/Pull%20Requests.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/git/Pull%20Requests.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by bradwillis** [comment]
@andreasblueher Please reach out to me at brwillis@microsoft.com and you can provide more details there.

**Comment by andreasblueher** [comment]
Is being resolved via email

**Comment by rbprado** [comment]
@andreasblueher Could you please paste the solution here?
Im trying to execute a patch with the following example, but it just set the completionOptions and not the "set auto-complete":
https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests/update?view=azure-devops-rest-5.0#enable_auto-completion_and_set_other_completion_options

**Comment by rbprado** [comment]
Ok, I found the issue here.
It's just about to send a json with:
{"autoCompleteSetBy": { "id": "xxxxxxxxxxxxxxxx"}}

**Comment by LucasCXavier** [comment]
@rbprado @darthwillis @andreasblueher 
Hey guys,
I'm trying to do the same thing but I'm getting the following error:
{
  "$id": "1",
  "innerException": null,
  "message": "Invalid argument value.\r\nParameter name: You can only update reviewers, descriptions, titles, merge status, and status.",
  "typeName": "Microsoft.TeamFoundation.SourceControl.WebServer.InvalidArgumentValueException, Microsoft.TeamFoundation.SourceControl.WebServer",
  "typeKey": "InvalidArgumentValueException",
  "errorCode": 0,
  "eventId": 0
}

I'm using the HTTP connector in Power Automate and this is the body:

{
  "autoCompleteSetBy": {
    "id": "xxxxxx"
  },
  "completionOptions": {
    "deleteSourceBranch": true
  },
  "lastMergeSourceCommit": {
    "commitID": "xxxxxxxxx",
    "url": "xxxxxxxx"
  }
}

If I try to add "status": "completed" in the body, it throws an error saying that the build validation must succeed to update the branch.

Thanks in advance for your help.

**Comment by walumo** [comment]
@LucasCXavier did you ever find a solution? I am getting the same exception in a similar situation when trying to patch autoCompleteSetBy

**Comment by LucasCXavier** [comment]
Hi @walumo,
I wasn’t able to set it to auto-complete as planned, but I did manage to complete it using the HTTP PATCH method in Power Automate.
