### ISSUE TITLE
It is unclear how to use the disabled flag

### ISSUE THREAD

**Issue by smithtad** [MicrosoftDocs/vsts-rest-api-specs#135]
The documentation for the Delete operation states that you can control whether or not deleted users should be returned using the disabled flag. There does not appear to be any other reference to this disabled flag or how to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e40952-bca9-9860-c1c5-1f422d2fc7fd
* Version Independent ID: f5dfb442-27fc-1d5f-a79c-d446e703b728
* Content: [Users (VSTS Graph)](https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/users?view=azure-devops-rest-5.0)
* Content Source: [docs-ref-autogen/5.0/graph/Users.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/5.0/graph/Users.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
@justmarks to help with this issue

**Comment by justmarks** [comment]
@smithtad thanks for calling this out.  We'll update the docs to be clearer here.  The correct way to see if a user is deleted is to check their membership (GetMembershipStateAsync - https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/membership%20states/get?view=azure-devops-rest-5.0) and if they are deleted, active will be equal to false

**Comment by smithtad** [comment]
@justmarks Thanks for the response. This is only useful, however, if you already have the subjectDescriptor. I can't get that for deleted/inactive users.

Ultimately what I'm trying to do is return a list of all users, including deleted users. The documentation for the users - delete endpoint [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/users/delete?view=azure-devops-rest-5.0) indicates that "Other GET calls, which may return multiple users, can control whether or not deleted users should be returned using the disabled flag, which defaults to false." The users - list endpoint doesn't appear to support this, however.
