### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by robbratton** [MicrosoftDocs/vsts-rest-api-specs#137]
Is there a NuGet package that wraps this API like the other Microsoft.TeamFoundation* packages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 180450be-094f-be87-f604-53922f26446d
* Version Independent ID: b695f17c-ce98-de26-40c3-5c9b569739b0
* Content: [Variablegroups (VSTS Task Agent)](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups?view=azure-devops-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/distributedTask/Variablegroups.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/distributedTask/Variablegroups.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
@robbratton here are the NuGet packages https://www.nuget.org/packages/Microsoft.TeamFoundation.DistributedTask.WebApi
