### ISSUE TITLE
How to use the Azure DevOps Security REST API to obtain permissions for a PAT token?

### ISSUE THREAD

**Issue by konrad-jamrozik** [MicrosoftDocs/vsts-rest-api-specs#138]
I have created a PAT token for `mseng` Azure DevOps organization following instructions given [here](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=vsts). How can I see if it gives me the permission to start a build in `mseng` ? 

I tried this: 

I executed command [documented here](https://docs.microsoft.com/en-us/rest/api/azure/devops/security/security%20namespaces/query?view=azure-devops-rest-5.0) to obtain security namespaces:

`GET https://dev.azure.com/mseng/_apis/securitynamespaces?api-version=5.0-preview.1`

The json had following data, among others:

key | value
-- | --
bit | 32
name | "START_BUILD"
displayName | "Start a build"
namespaceId | "<start_build_ns_id>"

Then I tried to call [the following](https://docs.microsoft.com/en-us/rest/api/azure/devops/security/permissions/has%20permissions%20batch?view=azure-devops-rest-5.0):

`POST https://dev.azure.com/mseng/_apis/security/permissionevaluationbatch?api-version=5.0-preview.1`

with body:
```
{
  "alwaysallowadministrators": false,
  "evaluations": [
    {
      "securitynamespaceid": "<start_build_ns_id>",
      "token": "<my_pat_token>",
      "permissions": 32
    }
  ]
}
```

and I got

```
{
    "evaluations": [
        {
            "securityNamespaceId": "<start_build_ns_id>",
            "token": "<my_pat_token>",
            "permissions": 32,
            "value": false
        }
    ]
}
```

I should have the permission to start a build. Is the response *false* event if the inputs were in incorrect format? Can I even pass PAT token as token? Do I have to base64 encode it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec02ac30-b36e-caf4-9e12-3de16de11789
* Version Independent ID: 50bad21a-9e2a-5d4b-337d-508e47f46fa5
* Content: [Security REST API for Azure DevOps Services - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/security/?view=azure-devops-rest-5.0)
* Content Source: [docs-ref-conceptual/5.0/security/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/5.0/security/index.md)
* Service: **vsts**
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by justmarks** [comment]
There is no way to see what permissions a given PAT has aside from trying the action and catching exceptions that would occur when it fails.  The PAT may fail for multiple reasons:
1. Lack of access for the user - NO PAT would work
2. PAT is expired/revoked
3. PAT doesn't have the required scopes (user has permission but PAT doesn't)

**Comment by konrad-jamrozik** [comment]
Thanks Justin. That answers my question, so I am closing the thread.
