### ISSUE TITLE
Can MSAL be used to authenticate to Azure DevOps?

### ISSUE THREAD

**Issue by rzulkoski** [MicrosoftDocs/vsts-rest-api-specs#139]

**Comment by wnjenkin** [comment]
@justmarks to help out here

**Comment by justmarks** [comment]
Azure DevOps does not yet support MSAL, we only support ADAL.  We have been told that MSAL is backwards compatible so there's a chance it may work but we haven't tested it yet.  Here's a sample of how to use ADAL: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-libraries
