### ISSUE TITLE
Release endpoints returning 404

### ISSUE THREAD

**Issue by damiangelis** [MicrosoftDocs/vsts-rest-api-specs#150]
Are release endpoints working? If I make a request to `_apis/build/builds?api-version=5.1-preview.5` I get results fine, but I have a 404 when I hit `_apis/release/releases?api-version=5.1-preview.5`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f88a412f-b63d-af24-2dc5-b72c79a87d4f
* Version Independent ID: 44a6c5d6-3f8a-563e-434d-e19ec337224e
* Content: [Releases (Release)](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases?view=azure-devops-rest-5.1)
* Content Source: [docs-ref-autogen/5.1/release/Releases.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/5.1/release/Releases.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by TianqiDONG** [comment]
hello,

how you solve this problem? also I get a 404 error page not found message...

**Comment by samtouray** [comment]
You need to use "vsrm" i.e. https://vsrm.dev.azure.com/<your_org>/ instead of https://dev.azure.com/<your_org>/ or $env:System_TeamFoundationServerUri instead of $env:System_TeamFoundationCollectionUri
