### ISSUE TITLE
Setting Access Control Entries result in Value cannot be null. Parameter name: container

### ISSUE THREAD

**Issue by MichelZ** [MicrosoftDocs/vsts-rest-api-specs#157]
I'm using:
`POST https://dev.azure.com/{organization}/_apis/accesscontrolentries/{securityNamespaceId}?api-version=5.0`

to set an ACE entry.

The body is:

```
{
      "token": "56c1c5bc-ffba-4956-b1f4-123455123456\69b44f3e-90a8-492f-a325-123456789012",
      "merge": true,
      "accessControlEntries": [
        {
          "descriptor": "Microsoft.IdentityModel.Claims.ClaimsIdentity;12345678-9257-4949-be1b-f83cfb83f65f\michel.zehnder@mycompany.com",
          "allow": 31,
          "deny": 0,
          "extendedinfo": {}
        }
  ]
}
```

The token is <projectid>\<teamid>
Security Namespace ID is 5a27515b-ccd7-42c9-84f1-54c998f03866 (identity)
I get the following message:

`{"$id":"1","innerException":null,"message":"Value cannot be null.\r\nParameter name: container","typeName":"System.ArgumentNullException, mscorlib","typeKey":"ArgumentNullException","errorCode":0,"eventId":0}`

[Documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/security/access%20control%20entries/set%20access%20control%20entries?view=azure-devops-rest-5.0) does not mention a parameter "container":

What am I doing wrong?

The goal is to set permissions for a User in a Group (Team)
The "underlying" goal is to add a new Team Administrator to a Team using this.

**Comment by MichelZ** [comment]
OK, got it. Looks like the Token and descriptor's backslash (\\) need to be escaped (\\\\)

**Comment by gotjaytoday** [comment]
Hi Michel,
May I ask what 56c1c5bc-ffba-4956-b1f4-123455123456 refers to in token? I guess 69b44f3e-90a8-492f-a325-123456789012 is the project id or the guid?

**Comment by MichelZ** [comment]
The token can be different things. In my case there it was <projectid>\<repoid>
