### ISSUE TITLE
Use Azure DevOps REST API to Delete organizations / accounts?

### ISSUE THREAD

**Issue by crpietschmann** [MicrosoftDocs/vsts-rest-api-specs#167]
Is it possible to Delete an organization / account within Azure DevOps using the REST API? You can delete other entities, but the documentation doesn't show a DELETE command for Accounts / Organizations.

Is this something that's possible?

I have a scenario where I need to automate the management of Azure DevOps Organizations across multiple users and Azure Subscriptions. I've also posted this question here: https://stackoverflow.com/questions/54793899/use-azure-devops-rest-api-to-delete-organizations-accounts

**Comment by wnjenkin** [comment]
@crpietschmann Unfortunately we don't support deleting organizations via our REST APIs. There currently isn't a way to automate this operation.
