### ISSUE TITLE
Another common task is "Searching for Files"

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-rest-api-specs#169]
please add that example. I can do this with the client libraries, but cannot find how to do it using the rest API

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393b7658-4cb2-087b-a323-37c40c8bbe24
* Version Independent ID: 76ce58c7-8f8a-eb60-d9c8-4eb64067db0e
* Content: [TFVC REST API for Azure DevOps Services - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/tfvc/?view=azure-devops-rest-5.0)
* Content Source: [docs-ref-conceptual/5.0/tfvc/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/5.0/tfvc/index.md)
* Service: **vsts**
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by wnjenkin** [comment]
@StingyJack are you looking for this api - https://docs.microsoft.com/en-us/rest/api/azure/devops/search/code%20search%20results/fetch%20code%20search%20results?view=azure-devops-rest-5.0 . If not, can you clarify what you're looking for?

**Comment by StingyJack** [comment]
@wnjenkin - probably. I'll try it later today if I can. Why is that not in the TFVC -> Items section?

**Comment by wnjenkin** [comment]
@StingyJack Code search is not specific to TFVC or GIT so we've grouped it under the global category of search.

**Comment by StingyJack** [comment]
A link to that on this page would help since a common task in either VCS would be searching for files.

**Comment by juangps96** [comment]
Is there any way to call the Lock Command from REST API?

**Comment by StingyJack** [comment]
@juangps96 - version control commands like that are available via an asmx/SOAP webservice (if you can believe it).   To see what the lock command looks like, start Fiddler and try running something like `tf vc lock .tfignore /lock:checkin`  (or whatever file if you dont have a .tfignore) and you will see the payload and endpoint. 

https://<your org>.visualstudio.com/VersionControl/v5.0/repository.asmx?wsdl  will give you the list of operations that are available. I would generate a client in whatever language you are using based on that wsdl and make the payload.  HTH

**Comment by juangps96** [comment]
Thanks Dear @StingyJack But this link: https://.visualstudio.com/VersionControl/v5.0/repository.asmx?wsdl  -   Give me: 403 Forbidden | nginx, any other link maybe?

**Comment by juangps96** [comment]
Dear @StingyJack,
For example, if I want to use operation Get or operation CheckIn; obviously I need to be previously authenticated, 
but, is there any example or way to do all the steps with ASMXs?

**Comment by StingyJack** [comment]
If you try running the tf commands while fiddler is running, I'm sure fiddler can capture that part too.  I've always just shelled out to cmd.exe since I was already local and had changes in a workspace. Working directly with a web service didn't seem like the right approach in my use cases, but I can see how it might be useful in others. Can you share your use case? There may be another way to do what you want.

I'd suggest that it may be useful to you is to see how the actual pages in devops communicate with version control, but I don't think locking is available on the web UI.
