### ISSUE TITLE
Why cant I pick the 1.0 api anywhere?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-rest-api-specs#17]
The docs are locked at 4.1. 

There isnt even a selector to pick something else.

**Comment by wnjenkin** [comment]
Thanks for your feedback! We're actively working to surface older documentation on docs.microsoft.com.

**Comment by StingyJack** [comment]
Are there any url tricks I can use to get the older ones?   TFS 2015 is still supported, and I have to work with it.

**Comment by wnjenkin** [comment]
Unfortunately there aren't any URL tricks, however we're close to surfacing older api versions. Will post the link here when the docs are live.

**Comment by wnjenkin** [comment]
Older api versions can be found on our docs site by accessing this link https://docs.microsoft.com/en-us/vsts/integrate/legacy-apis/overview?view=vsts .

**Comment by StingyJack** [comment]
TY !

**Comment by wnjenkin** [comment]
We've renamed the folder for these apis. Here is the new link https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/overview?view=vsts
