### ISSUE TITLE
Azure AD Graph API Reference leads to empty link.

### ISSUE THREAD

**Issue by Kalabric** [MicrosoftDocs/vsts-rest-api-specs#171]
The Azure AD Graph API Ref link in "For Azure DevOps Services customers backing their accounts with Azure Active Directory (AAD), management of AAD users and groups should be performed with the Azure AD Graph API Reference" leads to an error.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30241f0f-e9d4-68ea-b8ff-3aba3899bdbb
* Version Independent ID: bf7786bc-f0c4-74cf-a056-9bae37754f47
* Content: [Graph REST API for Azure DevOps Services - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/?view=azure-devops-rest-5.0)
* Content Source: [docs-ref-conceptual/5.0/graph/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/5.0/graph/index.md)
* Service: **vsts**
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by wnjenkin** [comment]
This issue has been resolved.
