### ISSUE TITLE
Annotated Tags - Get -500 

### ISSUE THREAD

**Issue by skoeg** [MicrosoftDocs/vsts-rest-api-specs#176]
Hi!

It seems when a tag has no description, the annotated tags get response is (**500**) Internal Server Error.

I'm working with tfs 2018 RTW - Version 16.122.27102.1
The requests api version parameter is: **api-version=4.0-preview**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 256ff798-fc87-eceb-b364-50fe7c23eebf
* Version Independent ID: d814b907-c6a5-c60c-5e4a-a31293ea2f42
* Content: [Annotated Tags (Azure DevOps Git)](https://docs.microsoft.com/en-gb/rest/api/azure/devops/git/annotated%20tags?view=vsts-rest-tfs-4.1#feedback)
* Content Source: [docs-ref-autogen/tfs-4.1/git/Annotated%20Tags.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/tfs-4.1/git/Annotated%20Tags.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by ParinSanghavi** [comment]
@skoeg can you provide following details?
1. Which endpoint are you trying to hit?
2. I am not sure which parameter are you referring to when you say, "when a tag has **no description**"- message, name or something else? 
3. Sample request URI and body and error details would be helpful

I tested the 'Create' endpoint without a message and it throws a 400 for me for 4.0 version. Please provide me the details to help me narrow down the issue. Let me know, thanks!

**Comment by skoeg** [comment]
@ParinSanghavi 

1. Annotated Tags - 'Get' endpoint
2. I'm referring to the tag message as description, sorry for the inconvenience.
3. I can't provide you more samples than this doc [Annotated Tags - Get](https://docs.microsoft.com/en-gb/rest/api/azure/devops/git/annotated%20tags/get?view=vsts-rest-tfs-4.1)

You will need a tag 'objectId' for the request when the tag with this identifier has no tag message an internal server error (500) occurs.

**Comment by pasangh** [comment]
(Parin Sanghavi changed account) By sample, I meant the URI you are trying to hit for the GET request that is giving you a 500. It'll help me with your account/ project/ repo names and check the validity of the object you are trying to get.

**Comment by pasangh** [comment]
@skoeg I made a fix to a show better error response. It'll be deployed in the next couple of weeks.

**Comment by RAJESWARAn18** [comment]
Uploaded my window
