### ISSUE TITLE
Previous (and more detailed) documentation can't be found

### ISSUE THREAD

**Issue by RafaelWO** [MicrosoftDocs/vsts-rest-api-specs#18]
I can't find the previous documentation for api version 1.0-3,0, e.g. https://www.visualstudio.com/en-us/docs/integrate/api/wit/work-items. I need the .NET client references to the REST API methods.

**Comment by wnjenkin** [comment]
Hi RafaelIWO! Our older documentation is now visible on the site and can be found here https://docs.microsoft.com/en-us/vsts/integrate/legacy-apis/overview?view=vsts .

**Comment by RafaelWO** [comment]
Thank you!

**Comment by RafaelWO** [comment]
@wnjenkin The link to the older documentation you mentioned 

> ([https://docs.microsoft.com/en-us/vsts/integrate/legacy-apis/overview?view=vsts](url))

is not working anymore... Is this only a temporary issue?

**Comment by wnjenkin** [comment]
This is a redirect issue due to a name change. Here is the new URL. https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/overview?view=vsts
