### ISSUE TITLE
Samples don't work

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-rest-api-specs#180]
I'm trying to list the task groups defined in our project and based upon the documentation for List it should be as simple as this: GET https://dev.azure.com/{{organization}}/{{project}}/_apis/distributedtask/taskgroups?api-version=5.1-preview.1 That URL returns ENOTFOUND when called by Postman's getaddrinfo.

Tried getting a specific one and got the same error. Tried reverting back to 5.0-preview.1 and 4.1-preview.1 They all return the same thing. Other APIs (like getting work item types) work correctly which seems to indicate either bad URLs or versioning. Security is properly set otherwise I would have expected a 401 or similar. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2f7fa61-510b-6b16-f32f-a341439709dc
* Version Independent ID: 862bb75c-1060-8e80-2a4f-efda9bffbcdd
* Content: [Taskgroups (Azure DevOps Task Agent)](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/taskgroups?view=azure-devops-rest-5.0)
* Content Source: [docs-ref-autogen/5.0/distributedTask/Taskgroups.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/5.0/distributedTask/Taskgroups.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by vithati** [comment]
@CoolDadTx , I am not able to repro the issue. I have tried same, it's working for me. Can you try once again and see it is working for you or not. 
example url: https://dev.azure.com/myorganizationname/MyFirstProject/_apis/distributedtask/taskgroups?api-version=5.1-preview.1

**Comment by CoolDadTx** [comment]
They might have fixed the APIs. Back several months ago when I wrote this up a lot of Azure DevOps APIs were failing across a lot of extensions as things seemed to get moved around. Unfortunately I've moved on and don't have time to revisit this issue. If it works for you then consider it closed.
