### ISSUE TITLE
Release definition API variable values are not transformed

### ISSUE THREAD

**Issue by ayayalar** [MicrosoftDocs/vsts-rest-api-specs#181]
When I call the GET release definition or release API, if I have a release or environment variable defined and assigned another variable, the value is not transformed.

Example:

If I have the following release variables:
```
Foo = 123
Bar = $(Foo)
```

The value I get back is `Bar=$(Foo)` where I would expect to see `Bar=123`

**Comment by wnjenkin** [comment]
@ayayalar Thanks for filing this issue. After speaking with the team that owns this api, this behavior is expected. Get calls don't materialize the variables. The variables are materialized only on running the release.
