### ISSUE TITLE
TFS2017/2018 docs

### ISSUE THREAD

**Issue by huntantr** [MicrosoftDocs/vsts-rest-api-specs#19]
How do I access the docs for TFS2017 and TFS2018. This information is only for VSTS so some is not applicable to TFS. I'm trying to create customizations for TFS and can no longer determine what REST API's are available and what api-version is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: 34a63078-bfe5-7cb5-e278-bf9edaa3fa4d
* Content: [Get started with the REST APIs for Visual Studio Team Services and Team Foundation Server - Visual Studio Team Services REST API](https://docs.microsoft.com/en-us/rest/api/vsts/#feedback)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Service: **unspecified**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by huntantr** [comment]
The version mapping I had, but that doesn't help with the new documentation, as I don't know what was available in those versions, now everything shows 4.1. I am currently running TFS2017.2 so I need to be able to see what api's are available in 3.2. 
Just like on the other documentation that has filtering based on whether it is VSTS, TFS2018, TFS2017, etc, the api's documentation requires this as well so that we can correctly see what is available to use. Being able to only see the latest for a version we are not even able to use is not helpful.
I am right in the middle of designing a customization and can't as I don't know what's available at my version.

**Comment by japj** [comment]
Perhaps going back in history and create a seperate branch per api version?
Or do you want to keep a single source tree with all api versions in it?

**Comment by huntantr** [comment]
The issue seems to be being handled in other parts of the documentation. I would recommend something like what is being down with powershell: https://docs.microsoft.com/en-us/powershell/scripting/powershell-scripting?view=powershell-6. Providing a filter for the API version would be extremely useful.

**Comment by wnjenkin** [comment]
Our older apis are now available on our docs site. They can be found here https://docs.microsoft.com/en-us/vsts/integrate/legacy-apis/overview?view=vsts. This should hopefully unblock your development.

**Comment by wnjenkin** [comment]
Ideally yes, these documents would appear in the same section but it's not as easy for us to do this right now. To unblock development ASAP, we've decided to port over a copy of our old documentation site. Going forward, we will have a version selector which allows you to toggle between different api versions and it will be applied to our standard location.

**Comment by huntantr** [comment]
That works for me. Thank you. I look forward to the final update to the docs.

**Comment by wnjenkin** [comment]
We've renamed the folder for these docs. Here is the new link https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/overview?view=vsts
