### ISSUE TITLE
Git diffs section documentation is incomplete

### ISSUE THREAD

**Issue by phun-ky** [MicrosoftDocs/vsts-rest-api-specs#20]
Especially the point for comparing between two commits. I would like to get the commits between two commits, but the documentation is incomplete

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4939520d-7d1a-0597-1461-c622175f40e2
* Version Independent ID: 5f10e5c8-4919-74b4-6f56-c0020b109f31
* Content: [Diffs (VSTS Git)](https://docs.microsoft.com/en-us/rest/api/vsts/git/diffs)
* Content Source: [docs-ref-autogen/git/Diffs.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/git/Diffs.yml)
* Service: **unspecified**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by vtbassmatt** [comment]
Same underlying issue as #15

**Comment by phun-ky** [comment]
If anyone in interested, here is a workaround:

https://gist.github.com/phun-ky/97bacd9f57e14acdaabecbdd03f13c5c

**Comment by vtbassmatt** [comment]
:+1: thanks @phun-ky.

**Comment by IdiotLeon** [comment]
I have have the same request: how to [easily] compare two commits, especially on the same file. Thanks.

**Comment by vtbassmatt** [comment]
@wnjenkin this should go to Joe Bourne now, not me. I don't have permission to unassign myself :)
