### ISSUE TITLE
VSTS Create Dashboard API

### ISSUE THREAD

**Issue by evanmcneal** [MicrosoftDocs/vsts-rest-api-specs#21]
Creating the simpler dashboard widgets using the create functionality works really well, however the more complicated widgets (CFD, BurnUp, and Velocity) always seem to give me an error about needing a "Type Id" before posting. The documentation says Type Id is deprecated and replaced by the Contribution Id. Either way, whether I have the Type Id or I don't include it in the jSon, the same error comes back saying that it can't be empty.  Just something to be aware of regarding creating widgets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24135945-2c86-d7cb-b800-f95b30b0beaa
* Version Independent ID: d4e01ce1-397c-47f3-59d9-8e0ca9bc86eb
* Content: [Widgets (VSTS Dashboard)](https://docs.microsoft.com/en-us/rest/api/vsts/dashboard/widgets)
* Content Source: [docs-ref-autogen/dashboard/Widgets.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/dashboard/Widgets.yml)
* Service: **unspecified**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by PeterAntal** [comment]
Hi Evan,

Got it, It sounds like the error handling is stale- can you describe which specific REST operation you were trying to exercise, so we can sanity check the details?

Thanks

**Comment by evanmcneal** [comment]
The VSTS Rest API I was using is the Create Widget function. The documentation is here: https://docs.microsoft.com/en-us/rest/api/vsts/dashboard/widgets/create

I used the create Dashboard function to throw up a dashboard and I was using this to append the widgets to it. I also tried the widgets in the dashboard creation and I received the same error.

**Comment by evanmcneal** [comment]
Also, I was doing a POST request. Sorry I forgot to mention that earlier.

**Comment by PeterAntal** [comment]
(For benefit of anyone reviewing this issue)
In touch with Evan over email also now... Requested the error message content, to isolate where in code the failure was produced.
