### ISSUE TITLE
Code Samples does not link to anything

### ISSUE THREAD

**Issue by SamBroner** [MicrosoftDocs/vsts-rest-api-specs#210]
The code samples link does not link to anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9af3a77-939e-b65c-9e48-80b36d7a6638
* Version Independent ID: 73d07604-0323-01ca-0f7d-db1545761c28
* Content: [Git REST API for Azure DevOps Services - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/?view=azure-devops-rest-5.0&viewFallbackFrom=azure-devops)
* Content Source: [docs-ref-conceptual/5.0/git/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/5.0/git/index.md)
* Service: **vsts**
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by seangwright** [comment]
Maybe it's supposed to go here?

https://github.com/microsoft/azure-devops-dotnet-samples/tree/master/ClientLibrary/Samples/Git
