### ISSUE TITLE
Attachments Created via API cannot be viewed correctly/corrupted file

### ISSUE THREAD

**Issue by elusivecube** [MicrosoftDocs/vsts-rest-api-specs#211]
Creating an attachment via /_apis/wit/attachments?api-version=5.0 endpoint does not retain the file's original content type and the file is not readable.

Each time after an attachment is created and associated to the workflow, when attempting to preview the file in DevOps, loader just keeps spinning.

Downloading the file locally (in our example is was a PNG file) and opening it on the desktop says "It looks like we don't support this file format", even though the file is a PNG file extension.

**Comment by mmanela** [comment]
@elusivecube  Can you share the code you used to attach the file? As long as you provide the file name to use we will use that to generate the proper content type on downloading.  /cc @obvioussean

**Comment by elusivecube** [comment]
I am attempting to use Microsoft Flow and the Send an HTTP request to Azure DevOps action to upload an attachment that is included in an Office 365 e-mail message that is retrieved via Flow trigger. 

I have a successful connection set up to the DevOps instance which I want to upload attachments to because I am able to create work items.

I am using the following for the Send an HTTP request to Azure DevOps action:

Method: POST
Relative URI: _apis/wit/attachments?fileName=GoldDeploy.PNG&api-version=5.0

The response I get:
Response Body:
`{
  "id": "1bf21ff4-0820-48f1-b0f5-9c9658f6d20f",
  "url": "<DEV OPS URL>/_apis/wit/attachments/1bf21ff4-0820-48f1-b0f5-9c9658f6d20f?fileName=GoldDeploy.PNG"
}`

The attachment that is retrieved from the e-mail gets uploaded correctly to Azure DevOps and I'm even making another HTTP request to DevOps to associate this attachment with the work item. It's after the attachment is uploaded that I'm not able to view it after it is downloaded. I can confirm that it doesn't seem to be the issue with the e-mail action because as a workaround to this, I am saving the attachment in a OneDrive folder and I am able to download and view the file from OneDrive without any issues.

**Comment by obvioussean** [comment]
@elusivecube Could you share the exact code you're using to upload the attachment?

**Comment by elusivecube** [comment]
@obvioussean -There is no code. I'm using Microsoft Flow.

I'm making a call to this endpoint to associate attachment to work item: _apis/wit/workitems/1119?api-version=5.0

I'm using PATCH as the method, headers: "application/json-patch+json"

Body:
`
[
  {
    "op": "add",
    "path": "/relations/-",
    "value": {
      "rel": "AttachedFile",
      "url": "<DEVOPSURL>/_apis/wit/attachments/0c89e641-1647-4ac2-90ef-2aa794dc747d?fileName=GoldDeploy.PNG",
      "attributes": {
        "comment": "Attachments"
      }
    }
  }
]
`
This part works fine.

**Comment by obvioussean** [comment]
@elusivecube You mean there is no code for uploading the attachment content to Azure DevOps?

**Comment by elusivecube** [comment]
Correct. Everything is done through Microsoft Flow.

**Comment by obvioussean** [comment]
@elusivecube Can you share your Flow with me?

**Comment by elusivecube** [comment]
@obvioussean  I'm sorry, but I cannot due to company policy. Do you have enough information to further investigate this?

**Comment by obvioussean** [comment]
@elusivecube I need more information,  could export it and scrub any sensitive information?

**Comment by elusivecube** [comment]
@obvioussean Sorry, been out on vacation. I'm trying to get you an example of the Flow of which I am using. I'd like to send you the zip file that I exported. Is there a way that I can send it to you directly rather than post it here? Thanks.

**Comment by obvioussean** [comment]
@elusivecube It's sferg at microsoft.com.

**Comment by elusivecube** [comment]
@obvioussean. Thanks. I'm going to send to an e-mail shortly.

**Comment by obvioussean** [comment]
Comparing the binary output of a Flow upload attachment vs an attachment uploaded from Azure DevOps, it appears Flow is sending extra data with the payload.  I'm not sure how much more I can investigate from the Azure DevOps side, it may be worth raising an issue with the Flow team.

**Comment by elusivecube** [comment]
@obvioussean thanks for investigating. Do you know where this issue could be logged for the Flow team?

**Comment by obvioussean** [comment]
@elusivecube I debugged, and Flow is sending the binary content as a string.  From their documentation it appears you can describe a connector with OpenAPI and from that you can tell it you want the content to be binary.

**Comment by elusivecube** [comment]
@obvioussean Thanks for the info. Can you please reference the documentation you are referring to? I'm curious because in the alternative that I have implemented, using OneDrive for Business, the content that I am retrieving from the email message and then invoking an action to create the file in OneDrive, I'm not running into these issues.

**Comment by obvioussean** [comment]
I'm not an expert on OpenAPI, but the OneDrive for Business is a connector that was internally written so it understands the binary inputs.  A random REST connector does not have the input.

I was using this as my reference:
https://powerusers.microsoft.com/t5/Building-Flows/Custom-API-to-file-upload/td-p/19938

**Comment by obvioussean** [comment]
This should also work since we support mime multipart for file upload:
http://johnliu.net/blog/2017/7/building-non-json-webservices-with-flow

**Comment by elusivecube** [comment]
@obvioussean Thanks. I'll let you know if I have any other questions.

**Comment by elusivecube** [comment]
@obvioussean on this page https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/attachments/create?view=azure-devops-rest-5.0, for the Upload a binary file example, in the example given for the request body it is indicated that it should be JSON, and the example provided is "[BINARY FILE CONTENT]". Can you please expand on this? Should this be base64encoded?

**Comment by obvioussean** [comment]
This unfortunately is more a side effect of our documentation system.  We expect binary content as the payload, not a json string.

**Comment by elusivecube** [comment]
Thanks for clarifying.

**Comment by ginzatron** [comment]
Has there been any resolution to your original problem? I am also creating a flow to send a base64 encoded file to an azure function that both posts the file(converted to a byte array) then patches it to the specified work item. Similarly, the file gets attached but the contents are always corrupted.

**Comment by tseluvki** [comment]
> This unfortunately is more a side effect of our documentation system. We expect binary content as the payload, not a json string or a base64 encoded string.

I have spent HOURS trying to get this to work, if I hadn't come across this post and this response, I never would have gotten it.  Please update your documentation.

**Comment by Bharatcv** [comment]
> This unfortunately is more a side effect of our documentation system. We expect binary content as the payload, not a json string or a base64 encoded string.

Hi @obvioussean : Could you please explain what it means ? how do we send binary content as the payload?  We have a similar  requirement to create an Azure Devops work item when a Form is submitted. The flow is working as expected, however the challenge is while attaching the document. There is no direct attachment option available. Is there any way we could do this.  I tried using "Send an HTTP request  to Azure Devops" but is throwing an error as I believe the parameters what is provided is wrong.

This is project requirement needed some immediate assistance. Please assist, thanks in advance.

**Comment by Bharatcv** [comment]
@tseluvki @elusivecube  May I know if you have got this to work ?  Please assist..

**Comment by tseluvki** [comment]
I did get it to work. I’m just using a google app script to create the json
and do the call:

**Comment by Dan-Newton** [comment]
This is a huge long shot since this issue is from 2020, but has anyone found a solution to this problem?

I have a logic app that takes email attachments and adds them to Azure DevOps as work item attachments. On the face of it the logic app runs perfectly without errors using two 'Send an HTTP request to Azure DevOps' actions:

- Upload (POST) the attachment (_apis/wit/attachments?fileName=<attachment-name>&api-version=6.0) with the email attachment content in the request body as base64ToBinary(body('Get_each_attachment')?['contentBytes'])

- Link (PATCH) the above HTTP request result to the work item (_apis/wit/workItems/<work-item-id>?api-version=6.0)

Text based attachments (e.g. .log or .txt files) work perfectly but image attachments, such as png, will not preview in DevOps and if downloaded to my PC I just get "It looks like we don't support this file format".

![image](https://github.com/MicrosoftDocs/vsts-rest-api-specs/assets/35452530/ee9f007d-3790-48fe-a9b1-50bb9b628b5a)
