### ISSUE TITLE
"-preview" should be removed form docs

### ISSUE THREAD

**Issue by ranjan-ranjan** [MicrosoftDocs/vsts-rest-api-specs#214]
![a](https://user-images.githubusercontent.com/16834561/57779724-4e7ff180-7744-11e9-9e7b-19c95248e407.png)

This issue may be present in other pages also

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da0d7182-ea0b-a67b-cc98-bf2c5935e504
* Version Independent ID: 279a0be2-a868-0374-70f5-b51588caf0fb
* Content: [Event Types (Azure DevOps Notification)](https://docs.microsoft.com/en-us/rest/api/azure/devops/notification/Event%20Types?view=azure-devops-rest-4.1#feedback)
* Content Source: [docs-ref-autogen/4.1/notification/Event%20Types.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/notification/Event%20Types.yml)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by tedchamb** [comment]
While most 5.0 APIs are released, there are some APIs that were introduced at 5.0, but were not ready to be released at the 5.0 release cutoff.  These are still marked as -preview in the docs, and will most likely be released in 5.1.   The 5.0-preview APIs will not change when called with the 5.0-preview api-version, but may change in 5.1 before they are marked as released.

**Comment by ranjan-ranjan** [comment]
![1](https://user-images.githubusercontent.com/16834561/57824642-5a59cb00-77b9-11e9-9a1f-1e32fc7d2149.png)

**Comment by tedchamb** [comment]
Same answer.   Each team decides when their API is at a point where they consider it 'released'.  Some teams take longer than others.

**Comment by ranjan-ranjan** [comment]
ok
