### ISSUE TITLE
Modifying pull request work items

### ISSUE THREAD

**Issue by GennadyGS** [MicrosoftDocs/vsts-rest-api-specs#22]
Thanks for cool API and documentation!
Is it possible (or will be possible) to modify attached work items with POST/PUT/PATCH/DELETE commands?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db99ecd-c056-34ad-ac0d-6cff18e9c4b2
* Version Independent ID: b8c0789d-12f1-e296-5b57-47369857627f
* Content: [Pull Request Work Items (VSTS Git)](https://docs.microsoft.com/en-us/rest/api/vsts/git/pull%20request%20work%20items)
* Content Source: [docs-ref-autogen/git/Pull%20Request%20Work%20Items.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/git/Pull%20Request%20Work%20Items.yml)
* Service: **unspecified**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by mmitrik** [comment]
@GennadyGS We don't have any near term plans to add more commands to the PR links API.  If you're interested in seeing invest in this, I'd encourage you to visit our [UserVoice forum](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/) to submit a suggestion.  This will give the item more visibility and allow others to add their support.

Thanks!
