### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by alejandro5042** [MicrosoftDocs/vsts-rest-api-specs#23]
Many of the links under "Pull Requests" (among others) in this document are broken (http 404) when rendered from: https://docs.microsoft.com/en-us/rest/api/vsts/git/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dda120f-ebb3-4bcc-f7c8-c8b867cba026
* Version Independent ID: ebee1395-ce8a-2485-d81c-3a286d0c2600
* Content: [Git REST API for Visual Studio Team Services (VSTS) - Visual Studio Team Services REST API](https://docs.microsoft.com/en-us/rest/api/vsts/git/)
* Content Source: [docs-ref-conceptual/git/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/git/index.md)
* Service: **vsts**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by wnjenkin** [comment]
This issue has been resolved. Please let me know if you are still experiencing issues.
