### ISSUE TITLE
Account APIs do not work

### ISSUE THREAD

**Issue by abettadapur** [MicrosoftDocs/vsts-rest-api-specs#24]
These APIs, copied and pasted from the documentation website, result in 404 errors. This needs to be fixed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2af3837-457c-4a7f-50c5-d2b8edcf904c
* Version Independent ID: 306d82ab-4128-0d37-cb8a-83e8321e3fe1
* Content: [Accounts (VSTS Accounts)](https://docs.microsoft.com/en-us/rest/api/vsts/account/accounts)
* Content Source: [docs-ref-autogen/account/Accounts.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/account/Accounts.yml)
* Service: **unspecified**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
Thank you for your feedback. We're actively working on a fix for this now.

**Comment by tedchamb** [comment]
@abettadapur To unblock you until the docs get updated, the correct host is 
`https://app.vssps.visualstudio.com` rather than `https://{accountName}.visualstudio.com`

**Comment by GrillPhil** [comment]
Using https://app.vssps.visualstudio.com I do get a 400 response saying "Necessary parameters ownerId or memberId were not provided in the request." Now I wonder how can I retrieve my member Id through the REST Api in order to construct this request?

**Comment by PiyushGuptaMSFT** [comment]
@abettadapur  Apologies for the inconvenience caused to you. Are you using https://app.vssps.visualstudio.com/_apis/accounts? The correct URI is https://app.vssps.visualstudio.com/_apis/accounts, however if you still getting an error using this, then please let us know.

**Comment by abettadapur** [comment]
Yes that API is working for me, thanks

**Comment by PiyushGuptaMSFT** [comment]
@abettadapur Just to add on, if you want to retrieve your id, you can use the connectionData api https://app.vssps.visualstudio.com/_apis/ConnectionData, to get your id, and then called the https://app.vssps.visualstudio.com/_apis/accounts?ownerId={ownerId}&api-version={api-version}, to find the accounts associated with the id. This is the recommended way to use List Accounts API, as you will get the concise account object in response.

**Comment by abettadapur** [comment]
@PiyushGuptaMSFT Additionally, I cannot use my PAT to call this API. The same PAT works correctly on the other account scoped APIs

**Comment by PiyushGuptaMSFT** [comment]
@abettadapur Currently, PAT creation is scoped to accounts, and hence it is not possible to call an deployment level API via PAT.

**Comment by crpietschmann** [comment]
I can call "_apis/ConnectionData" and pass the PAT for success. However, no matter what I do when I call "_apis/accounts" it ALWAYS returns 401 Unauthorized... Is the API broken?

FYI, I'm using Postman right now to do the calls. Will write code once I get the right calls working...

**Comment by crpietschmann** [comment]
> @abettadapur Currently, PAT creation is scoped to accounts, and hence it is not possible to call an deployment level API via PAT.

How can we make an API call to get a list of the Accounts / Organizations the current user has access to in Azure DevOps, if the PAT wont work with "_apis/accounts"??

**Comment by and-megan** [comment]
Using `https://app.vssps.visualstudio.com/_apis/accounts` I get the `"Necessary parameters ownerId or memberId were not provided in the request."` response. I am using an OAuth token. I am using version 5.0 of the AzureDevops REST API.

**Comment by matejskubic** [comment]
@PiyushGuptaMSFT any news on this?
Request `https://app.vssps.visualstudio.com/_apis/accounts?api-version=7.2-preview`
still returns

```
{
  "$id": "1",
  "innerException": null,
  "message": "Necessary parameters ownerId or memberId were not provided in the request.",
  "typeName": "Microsoft.VisualStudio.Services.Account.AccountException, Microsoft.VisualStudio.Services.WebApi",
  "typeKey": "AccountException",
  "errorCode": 0,
  "eventId": 4236
}
```
