### ISSUE TITLE
Release endpoints returning 404 error

### ISSUE THREAD

**Issue by jashan05** [MicrosoftDocs/vsts-rest-api-specs#268]
Are release endpoints working? If I make a request to _apis/build/builds?api-version=5.1-preview.5 I get results fine, but I have a 404 when I hit _apis/release/releases?api-version=5.1-preview.5.

**Comment by wnjenkin** [comment]
@jashan05 are you still experiencing this issue?

**Comment by jashan05** [comment]
@wnjenkin Could you please update on this issue

**Comment by wnjenkin** [comment]
Adding @shashban to take a look

**Comment by shashban** [comment]
Can you confirm you are using vsrm.dev.azure.com as the hostname for the call?
like https://**vsrm.dev.azure.com**/{organization}/{project}/_apis/release/releases?api-version=5.1

**Comment by jashan05** [comment]
Thanks @shashban i was missing the **vsrm** in my URL.
