### ISSUE TITLE
How does one get the `reviewerId` to pass to the Create Pull Request Reviewer API?

### ISSUE THREAD

**Issue by dg42xyz** [MicrosoftDocs/vsts-rest-api-specs#294]
I cannot find any APIs that returned a valid `reviewerId` that is required for the Create Pull Request Reviewer API.  The IDs that returned from the Users - Get operation in the Graph service are not even valid.  So how am I supposed to get a reviewerId?

**Comment by dg42xyz** [comment]
I figured this out.  The documentation could use some improvement though.

**Comment by MO2k4** [comment]
@dg42xyz How did you do it?

**Comment by dg42xyz** [comment]
What I eventually found was that you cannot create a Pull Request Reviewer record for a different user than what the API call is executing under. I was trying to have a service account create a PR reviewer on behalf of another user based on an action in a different system.

However the way to dynamically get a valid `reviewerId` guid to pass to the Create Pull Request Reviewer API was this:
	1. Call the Groups - List API for a group that you know the user is a part of (for me it was the Project Valid Users group): https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/groups/list?view=azure-devops-rest-5.1
	2. User the originId from that response to call the Core - Teams Get Team Members with Extended Properties: https://docs.microsoft.com/en-us/rest/api/azure/devops/core/teams/get%20team%20members%20with%20extended%20properties?view=azure-devops-rest-5.1
	3. Finally use the id of the desired user to call the Create Pull Request Reviewer
