### ISSUE TITLE
OpenAPI Specification?

### ISSUE THREAD

**Issue by SeanCLeavitt** [MicrosoftDocs/vsts-rest-api-specs#324]
Is there an OpenAPI Specification available for each of these REST APIs?  It would be very helpful to have links available to them from this page.  Thank you, Sean

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: f74b7d51-aede-ed93-437e-601654d8fa7e
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.0)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by MarcosMeli** [comment]
@SeanCLeavitt: The specs are here https://github.com/MicrosoftDocs/vsts-rest-api-specs
