### ISSUE TITLE
Pre-Version 4.1 REST API documentation gives 404 Not Found Response

### ISSUE THREAD

**Issue by ilmaestro** [MicrosoftDocs/vsts-rest-api-specs#33]
What happened to the Pre-Version 4.1 REST API docs?  Specifically looking for version 3, for On-premise TFS 2017. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: 34a63078-bfe5-7cb5-e278-bf9edaa3fa4d
* Content: [Get started with the REST APIs for Visual Studio Team Services and Team Foundation Server - Visual Studio Team Services REST API](https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1#where-are-the-earlier-versions-of-rest-apis-before-41)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Service: **vs-devops-alm**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by wnjenkin** [comment]
Our 4.1 rest api's can be found here https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1

**Comment by wnjenkin** [comment]
Previous rest api versions can be found here https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/overview?view=vsts

**Comment by wnjenkin** [comment]
@ilmaestro did these links resolve the issue you were encountering?

**Comment by ilmaestro** [comment]
@wnjenkin, it looks like the previous-api's link shows docs for v1.0 and 2.0 of the Api.  I'm still not able to find any documentation specific to version 3.0.  The only thing I've been able to do is use the 4.1 documentation and try different previews, for example 3.2-preview.2 seems to work with most of the 4.1 docs. So i've been working around it.  It would be nice if there was a document describing which of the 3.x versions supported which features. but that's a separate issue. 

I don't think we can close this issue, because the link I'm referring to, as reported on this page (https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1#where-are-the-earlier-versions-of-rest-apis-before-41), is still set to : https://docs.microsoft.com/en-us/vsts/integrate/legacy-apis/overview?view=vsts-rest-4.1  which is giving the 404 not found.  It sounds like the /legacy-apis/ part of the url should be changed to /previous-apis/

**Comment by wnjenkin** [comment]
Yes it should be changed to previous-apis. Yes this needs to be updated. Fixing this now.

**Comment by wnjenkin** [comment]
This issue has been resolved.
