### ISSUE TITLE
Java REST API client

### ISSUE THREAD

**Issue by vinx13** [MicrosoftDocs/vsts-rest-api-specs#334]
API SDK for some languages like Python are provided, but I didn't find Java client. Is Java client available? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: f74b7d51-aede-ed93-437e-601654d8fa7e
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1#feedback)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by haokanga** [comment]
To add more context:

- There is [Java Client for Azure REST](https://docs.microsoft.com/en-us/java/api/overview/azure/?view=azure-java-stable); 
- and there are clients for other languages for [Azure DevOps REST] (https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1#client-libraries). 
- However, no Java client for Azure DevOps REST
