### ISSUE TITLE
How does one create a build definition through the C# Client Library?

### ISSUE THREAD

**Issue by anh-duc-le** [MicrosoftDocs/vsts-rest-api-specs#34]
I'm at a complete loss on how to create a build definition via the C# Client Library.

As far as I understand, the Steps property and other important properties all happen to be readonly? 

    namespace Microsoft.TeamFoundation.Build.WebApi    
        { 
        [DataContract]    
        public class BuildDefinition : BuildDefinitionReference
            {
                public BuildDefinition();
    
                public List<string> Tags { get; }
                public PropertiesCollection Properties { get; }
                public List<RetentionPolicy> RetentionRules { get; }
                public List<Demand> Demands { get; }
                public IDictionary<string, BuildDefinitionVariable> Variables { get; }
                public List<BuildTrigger> Triggers { get; }
                public ProcessParameters ProcessParameters { get; set; }
                public BuildRepository Repository { get; set; }
                public List<BuildOption> Options { get; }
                public List<BuildDefinitionStep> Steps { get; }
                public bool BadgeEnabled { get; set; }
                public int JobTimeoutInMinutes { get; set; }
                public BuildAuthorizationScope JobAuthorizationScope { get; set; }
                public string DropLocation { get; set; }
                public string Description { get; set; }
                public string Comment { get; set; }
                public string BuildNumberFormat { get; set; }
                public Build LatestBuild { get; }
                public Build LatestCompletedBuild { get; }
            }
         }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71158dd-5587-9550-a56d-6bdeeb85c703
* Version Independent ID: 89dced11-b00b-1c6e-ab5a-5d69b6bcd2eb
* Content: [Definitions (VSTS Build)](https://docs.microsoft.com/en-us/rest/api/vsts/build/definitions?view=vsts-rest-5.0)
* Content Source: [docs-ref-autogen/5.0/build/Definitions.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/5.0/build/Definitions.yml)
* Service: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by scottdallamura** [comment]
1. That looks like a really old version of the contract. Newer versions don't have Steps, they have a list of Phases.

2. You don't need to set the lists.  You'll note that they are never null (they're created on first access) so you can add to them:
`
var definition = new BuildDefinition();
definition.Steps.Add(new BuildDefinitionStep() { ... });
`

**Comment by mikaelkrief** [comment]
@scottdallamura I can't see the definition phases in the Rest Api spec

**Comment by dragan-bjelosevic** [comment]
Accessing Azure Devops with .Net client library is a nightmare. I never touched anything so poorly documented and explained
