### ISSUE TITLE
ADAL is not the recommended SDK for Microsoft identity, MSAL is

### ISSUE THREAD

**Issue by bgavrilMS** [MicrosoftDocs/vsts-rest-api-specs#353]
Please stop using / recommending ADAL as the library of choice for getting tokens. ADAL is slowly being deprecated in favour of MSAL (e.g. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: f74b7d51-aede-ed93-437e-601654d8fa7e
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by marcpopMSFT** [comment]
We're aware of the transition but do not have plans to move onto ADAL at this time as we're limiting changing in the identity space.  We'll review this in the future.
