### ISSUE TITLE
Missing left pane with a list of links (Non-API 5.1)

### ISSUE THREAD

**Issue by kozhemyak** [MicrosoftDocs/vsts-rest-api-specs#355]
The documentation for non-latest API is broken. There is no list of links on the left side of the website. Engineers cannot use the docs for the previous API. The workaround is to select the required API with the latest and switch to the legacy version.

Links for instance:
https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-4.1
![image](https://user-images.githubusercontent.com/26633375/76084854-0b488500-5fdb-11ea-935a-da1abc338b6a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: f74b7d51-aede-ed93-437e-601654d8fa7e
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-4.1&source=docs)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by sobjornstad** [comment]
+1, this needs prompt attention since anyone not on the latest version cannot use the API documentation (or has to guess about what is accurate on older versions).

**Comment by balfa666** [comment]
Please add links to documentation

**Comment by kozhemyak** [comment]
> Please add links to documentation

It is already in the body of the request. A bit below the main issue.

**Comment by kozhemyak** [comment]
Solved.
