### ISSUE TITLE
There is a way to delete an attachment?

### ISSUE THREAD

**Issue by JenniferPerezBedoya** [MicrosoftDocs/vsts-rest-api-specs#36]
If I've created an attachment and for some reason the work item that will be linked to the attachment fails, then how can I do to delete the attachment? Or there is a live time configured for the attachment?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 3820511c-6eab-cad8-7ac3-f8ec8ae5bd25
* Version Independent ID: 1ac50084-2157-2ee2-1fff-a064735c17b9
* Content: [Attachments (VSTS Work Item Tracking)](https://docs.microsoft.com/es-es/rest/api/vsts/wit/attachments?view=vsts-rest-5.0)
* Content Source: [docs-ref-autogen/5.0/wit/Attachments.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/5.0/wit/Attachments.yml)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by saritwik** [comment]
Attachments with no association to work items get cleaned up by the system after 30 days. You cannot explicitly delete attachments.

**Comment by JenniferPerezBedoya** [comment]
Perfect, thank you so much.
