### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by Te7a-Houdini** [MicrosoftDocs/vsts-rest-api-specs#40]
When i try https://{accountName}.visualstudio.com/_apis/profile/profiles/{id}?api-version=5.0-preview.3  
it gives page not found . 

but when i add .vssps and try , it works 
https://{accountName}.vssps.visualstudio.com/_apis/profile/profiles/{id}?api-version=5.0-preview.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80c8966e-925d-f22f-258d-bf4ce47dda76
* Version Independent ID: c396729b-267b-5df7-e21a-dac32aa7b83c
* Content: [Profiles REST API for Visual Studio Team Services (VSTS) - Visual Studio Team Services REST API](https://docs.microsoft.com/en-us/rest/api/vsts/profile/?view=vsts-rest-5.0)
* Content Source: [docs-ref-conceptual/5.0/profile/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/5.0/profile/index.md)
* Service: **vsts**
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by wnjenkin** [comment]
Closing since the docs have been updated to reflect this change
