### ISSUE TITLE
Documentation for linking a work item to pull request is gone

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/vsts-rest-api-specs#41]
In the old documentation, there used to a page for linking a work item to pull request, now the link just reroute to the top git level page.
Issue Details
Please either add it to the pull request section or add it as an example to the work item update section
The issue is transferred from https://github.com/MicrosoftDocs/feedback/issues/337

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5e4fa50-af73-0d76-ed1a-fdc2e53682fd
* Version Independent ID: ebee1395-ce8a-2485-d81c-3a286d0c2600
* Content: [Git REST API for Visual Studio Team Services (VSTS) - Visual Studio Team Services REST API](https://docs.microsoft.com/en-us/rest/api/vsts/git/?view=vsts-rest-4.1#adding-a-work-item-link)
* Content Source: [docs-ref-conceptual/4.1/git/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/4.1/git/index.md)
* Service: **vsts**
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by wnjenkin** [comment]
Hi @Powerhelmsman the api to link a work-item to apull request can be found here https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/git/pull-requests/work-items?view=vsts .
