### ISSUE TITLE
Add Code Sample for ADAL

### ISSUE THREAD

**Issue by heinrich-ulbricht** [MicrosoftDocs/vsts-rest-api-specs#424]
The code sample column for ADAL states "sample (coming soon)". The page has last been updated 4 years ago. 

![image](https://user-images.githubusercontent.com/3469970/91172061-e0aecd80-e6db-11ea-8b20-d6b22604f1d7.png)

Is the documentation up-to-date? Is there a sample for us you could link to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: f74b7d51-aede-ed93-437e-601654d8fa7e
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.0)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by heinrich-ulbricht** [comment]
This page seems to be more up-to-date: https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance?view=azure-devops

And it also states that it's valid for Azure DevOps Services. Should this page be linked instead of the (old) table?

**Comment by nechvatalp** [comment]
The page has been updated and has MSAL samples now.
