### ISSUE TITLE
Please restore API Version 3.x. IT's not that old and we run On PREM

### ISSUE THREAD

**Issue by Wil73** [MicrosoftDocs/vsts-rest-api-specs#43]
Please include earlier API versions.  We run ON PREM and this API reference is very handy, but we only run TFS 2017 at the moment.  I can certainly understand removing much older documentation, but an API reference for a version that is only a year old should not be removed this early.  Please restore at least API 3.x   Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e0e4592-552c-29ea-d7c6-4852a220839e
* Version Independent ID: 09782bbf-ccf1-dde1-a16c-92a3787c34e1
* Content: [Release REST API for Visual Studio Team Services (VSTS) - Visual Studio Team Services REST API](https://docs.microsoft.com/en-us/rest/api/vsts/release/?view=vsts-rest-4.1)
* Content Source: [docs-ref-conceptual/4.1/release/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/4.1/release/index.md)
* Service: **vsts**
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by wnjenkin** [comment]
Previous versions of our APIs can be found here - https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/overview?view=vsts&viewFallbackFrom=vsts-rest-4.1

**Comment by Wil73** [comment]
That is incorrect.  What I wrote was for 3.1 which is for TFS 2017.  Please read my ticket carefully.  Your link is for 4.1 which does not help.

**Comment by wnjenkin** [comment]
@Wil73 While the URL contains 4.1, this link contains all of our previous documentation.  Please click one of the links under "Common Rest APIs and Usage" or "Full list of Rest APIs" and you will see our previous API. Let me know if there is a particular API you are looking for and I can provide a direct link.

**Comment by Wil73** [comment]
I am looking in particular for API for TFS 2017 pertaining to build and build definitions.. on PREM TFS, not VSTS

**Comment by Wil73** [comment]
Yes that is the source of the confusion: v4 and v5 are layed out quite well, but the previous version info is rather convoluted.  I can see it now thanks.
