### ISSUE TITLE
Stylize Card Rule Settings for Iteration Board (TaskBoard)

### ISSUE THREAD

**Issue by evanmcneal** [MicrosoftDocs/vsts-rest-api-specs#44]
I am inquiring about VSTS API calls to stylize the TaskBoard (Sprint Board) to have custom styles and fields. I Have done this on the backlogs and boards, but I can not seem to do this to the TaskBoard. Even the API call to List the Boards does not return the TaskBoard as part of the payload it sends back. Is there going to be the ability to use the APIs to stylize this board in the future? It would be a great feature to allow our company to standardize sprint boards across out teams. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2231eab0-a121-d05d-7146-6bbf2cec3ddd
* Version Independent ID: d7e1190a-791d-237b-0ff3-2a62d2b77749
* Content: [Cardrulesettings (VSTS Work)](https://docs.microsoft.com/en-us/rest/api/vsts/work/cardrulesettings?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/work/Cardrulesettings.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/work/Cardrulesettings.yml)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by smithago** [comment]
Thank you for reporting the issue. For historical reasons we have not created this API in the new REST standards. We will be fixing it as we are working on supporting custom columns for taskboard. Unfortunately we do not have a workaround for it. 

smithasa@microsoft.com
