### ISSUE TITLE
Environments documentation does not list required PAT scope

### ISSUE THREAD

**Issue by ni-gpapp** [MicrosoftDocs/vsts-rest-api-specs#441]
According to the operation pages of the Environments documentation those REST APIs can be used with a personal access token, and there's no additional requirement listed under Security. However, they work only if the PAT has the Tokens, or the Token Administration scope added to it, otherwise give 401 Unauthorized as a response.

Please list the required scope(s) on these pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 844617a7-c5ae-5a37-11ed-58f35df32b4b
* Version Independent ID: a4504a16-1db1-abd1-cb35-6f1ce1cc8c35
* Content: [Environments (Azure DevOps Task Agent)](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/environments?view=azure-devops-rest-6.0)
* Content Source: [docs-ref-autogen/6.0/distributedTask/Environments.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/6.0/distributedTask/Environments.yml)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by nechvatalp** [comment]
@ni-gpapp new API version now contain the required scope. Thanks for reporting the issue.
https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/environments/add?view=azure-devops-rest-7.1#scopes
