### ISSUE TITLE
Looking for link to auth documentation

### ISSUE THREAD

**Issue by michaellperry** [MicrosoftDocs/vsts-rest-api-specs#444]
I landed on this API from a task-based search. I would like to start coding against this service, but I cannot find a link to a page describing how to get started. I would like to know how the API authenticates, how to find my organization and project identifier from the Azure DevOps portal or URL, and other introductory concepts. If such a page already exists, I cannot find it in the navigation sidebar from this API documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca2b066c-7301-a209-c1b0-b9ce2b4cd64d
* Version Independent ID: d0898134-f5ac-2f09-1f11-25ca5573235b
* Content: [Build REST API for Azure DevOps Services - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/?view=azure-devops-rest-6.0#feedback)
* Content Source: [docs-ref-conceptual/6.0/build/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/6.0/build/index.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by nechvatalp** [comment]
@michaellperry We have two sample repositories which might be useful.

- https://github.com/microsoft/azure-devops-auth-samples Authentication in ADO
- https://github.com/microsoft/azure-devops-dotnet-samples C# Samples

**Comment by michaellperry** [comment]
Thank you. I did eventually find the information I needed. Adding these links to the page might be helpful for the next person. I was unable to find the .md file to make a PR.
