### ISSUE TITLE
Patch Option for Taskgroup

### ISSUE THREAD

**Issue by osanam-giordane** [MicrosoftDocs/vsts-rest-api-specs#449]
I would like to know if Microsoft estimate allow patch for task group preview using azure devops api´s?

https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/taskgroups?view=azure-devops-rest-6.1

**Comment by nechvatalp** [comment]
@osanam-giordane Are you asking if we will have API to update usign PATCH? Currently there is no such plan.
