### ISSUE TITLE
Adding users in VSTS with the Graph API seems broken

### ISSUE THREAD

**Issue by rvanmaanen** [MicrosoftDocs/vsts-rest-api-specs#45]
Hi,

I created 2 requests in Postman, one to get users and one to add users. Both requests contain the Authorization header with the base64 encoded PAT. The GET seems to work and I receive a list of users, when I POST the response is a 201 Created with all the expected data there, but it has no effect. No users are created and they can't login either. The result of the GET operation remains the same and nothing is visible in the portal.

The body I'm sending is quite basic:
```
{
  "principalName": "rvanmaanen@xpirit.com"
}
```

The response seems to be ok:
```
{
    "subjectKind": "user",
    "metaType": "member",
    "metadataUpdateDate": "2018-03-23T13:44:45Z",
    "domain": "3d4d17ea-1ae4-4705-947e-51369c5a5f79",
    "principalName": "rvanmaanen@xpirit.com",
    "mailAddress": "rvanmaanen@xpirit.com",
    "origin": "aad",
    "originId": "1d5edea4-78d4-4db8-bce1-a0a6519f9323",
    "displayName": "Reinier van Maanen",
    [removed]
}
```

Can you tell me what I'm doing wrong?

With regards,

Reinier van Maanen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7db6d9-076e-6285-fe34-1746300c31e9
* Version Independent ID: cb1bdc40-00ec-fc20-ddbc-8f69910ddc01
* Content: [Users (VSTS Graph)](https://docs.microsoft.com/en-us/rest/api/vsts/graph/users?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/graph/Users.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/graph/Users.yml)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by justmarks** [comment]
Adding a user via Graph does not give them access to the account, the user has to be materialized and added to the appropriate projects, groups etc.  To shortcut this, we have a different API, [Member Entitlement](https://docs.microsoft.com/en-us/rest/api/vsts/memberentitlementmanagement/user%20entitlements/add?view=vsts-rest-4.1), that does this for you.  I suggest giving that a shot for adding users instead.
