### ISSUE TITLE
GetAsync example missing dollar sign for interpolation. 

### ISSUE THREAD

**Issue by zack-at-ds2** [MicrosoftDocs/vsts-rest-api-specs#451]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: f74b7d51-aede-ed93-437e-601654d8fa7e
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by nechvatalp** [comment]
@zack-at-ds2 It is just a sample the user is supposed to change the value with his organization it is not using interpolation.

**Comment by zack-at-ds2** [comment]
> @zack-at-ds2 It is just a sample the user is supposed to change the value with his organization it is not using interpolation.

Almost two years later... why bother with this non-response?
