### ISSUE TITLE
Token Get Personal Access Token GET or POST? Says GET, but examples is a POST.

### ISSUE THREAD

**Issue by mattruma** [MicrosoftDocs/vsts-rest-api-specs#454]
The docs seem to point to this call being a GET, but the examples show it as a POST, but there is no definition for the Body? Just curious what it really is GET or POST? And if a POST, what does the body look like?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb23d5f-ec98-08df-ceaa-f33e91f5fbe1
* Version Independent ID: 52ad5fb5-21bf-a9ed-c410-9e076bc05c72
* Content: [Token Get Personal Access Token (Azure DevOps Token Admin)](https://docs.microsoft.com/en-us/rest/api/azure/devops/tokenadmin/token%20get%20personal%20access%20token?view=azure-devops-rest-6.0)
* Content Source: [docs-ref-autogen/6.0/tokenAdmin/Token Get Personal Access Token.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/6.0/tokenAdmin/Token Get Personal Access Token.yml)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by mattruma** [comment]
Any thoughts on this?

**Comment by nechvatalp** [comment]
@mattruma Hi the link is not working and I couldn't find it. When looking at PAT documentation now I cannot see any example using POST.

I guess it has been resolved.
