### ISSUE TITLE
How to reproduce "git diff commitA commitB -- file" with VSTS?

### ISSUE THREAD

**Issue by WladdGorshenin** [MicrosoftDocs/vsts-rest-api-specs#46]
I like to use VSTS API for my project, because it provides me with all functions I need. Thank you for the great tool!

Nevertheless I got a new challenge and would like to ask for advice, what would be the best recipe to reproduce 'git diff commitA commitB -- file' results with VSTS? My goal is for each tuple (commit, overlapping_commit, file) find out the number of lines in the file touched by both commits?

**Comment by mmitrik** [comment]
I think the best way to do this right now is to create a branch or tag that points to the commits you're interested in, and the use the Compare branches from the Branches page or Compare tags from the Tags page.  That will give you both the list of commits and the changed files.  

If you're looking for a way to do this strictly through the API, I think this is the API you want to use: https://docs.microsoft.com/en-us/rest/api/vsts/git/diffs/get?view=vsts-rest-4.1#between_commit_ids

**Comment by WladdGorshenin** [comment]
Hi @mmitrik, thank you for the reply. Now I understand the situation.
