### ISSUE TITLE
Allow for process-specific request?

### ISSUE THREAD

**Issue by BillRaymond** [MicrosoftDocs/vsts-rest-api-specs#47]
It would be great if the API provided you with the ability to get the icon, the color, or the icon with the color (a red insect representing a bug in a specific process, for example).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8375cd9-81fa-3f80-6d86-42c5f6093f5f
* Version Independent ID: e0b6c619-126e-4487-cbfe-79b68c2aee52
* Content: [Work Item Icons (VSTS Work Item Tracking)](https://docs.microsoft.com/en-us/rest/api/vsts/wit/work%20item%20icons?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/wit/Work%20Item%20Icons.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/wit/Work%20Item%20Icons.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
@mmanela passing this feedback along.

**Comment by chataylor** [comment]
@BillRaymond Hi there! There is an [existing API ](https://docs.microsoft.com/en-us/rest/api/vsts/wit/work%20item%20types/get?view=vsts-rest-4.1#response)which returns the information you requested. Please do let me know if there is anything we could have done better to improve the documentation or its discoverability.

**Comment by BillRaymond** [comment]
The documentation allows you to list out all the work item icons, but what if you want to get the specific work item type for a process rather than just the default settings?

For example, this is how the API works now to get a list of work item icons:
https://{accountName}.visualstudio.com/_apis/wit/workitemicons?api-version=4.1-preview.1<http://visualstudio.com/_apis/wit/workitemicons?api-version=4.1-preview.1>


What I am requesting is the list of work item icons for a specific inherited process, with something like this:
https://{accountName}.visualstudio.com/_apis/wit/<http://visualstudio.com/_apis/wit/>{processName}?workitemicons?api-version=4.1-preview.1<http://visualstudio.com/_apis/wit/workitemicons?api-version=4.1-preview.1>

And when calling the GET API, this is what it looks like to specify the icons and colors:
https://{accountName}.visualstudio.com/_apis/wit/workitemicons/<http://visualstudio.com/_apis/wit/workitemicons/>{icon}?color={color}&v={v}&api-version=4.1-preview.1

What I am requesting would look something like this:
https://{accountName}.visualstudio.com/_apis/wit/workitemicons/<http://visualstudio.com/_apis/wit/workitemicons/>{process}/{icon}?v={v}&api-version=4.1-preview.1

In the first example, I would only receive a list of work item icons that exist in the given process.

In the second example, I would receive the icon with the color already specified by the administrator that created the inherited process.


-Bill
Bill Raymond
Cambermast LLC
+1 (415) 305-2595

www.cambermast.com<http://www.cambermast.com>
Portfolio: http://bit.ly/2ks6uGO
bill.raymond@cambermast.com
@billraymonde
GitHub: BillRaymond

Writing: http://techgenix.com/author/braymond/

On Jun 4, 2018, at 3:07 PM, Charles Taylor <notifications@github.com<mailto:notifications@github.com>> wrote:


@BillRaymond<https://github.com/BillRaymond> Hi there! There is an existing API <https://docs.microsoft.com/en-us/rest/api/vsts/wit/work%20item%20types/get?view=vsts-rest-4.1#response> which returns the information you requested. Please do let me know if there is anything we could have done better to improve the documentation or its discoverability.

**Comment by chataylor** [comment]
@BillRaymond Hi there! Sorry about the delay in response. I see that you're attempting to get process-specific information on work item icons and colors. You can retrieve this information via our process definition APIs, specifically [Get Work Item Types](https://docs.microsoft.com/en-us/rest/api/vsts/processdefinitions/work%20item%20types/get%20work%20item%20types?view=vsts-rest-4.1). These process definition APIs are still in preview, however, so do be aware of this as our team is still working to finalize plans here.

**Comment by BillRaymond** [comment]
@chataylor Thank you! Can you give a sense as to when the APIs will be out of preview? I understand if you cannot commit to a date so just looking for a general sense. Thanks again.
