### ISSUE TITLE
Many Overview topic links are broken in TOC due to ".yml" suffix

### ISSUE THREAD

**Issue by ChadMcCaffery** [MicrosoftDocs/vsts-rest-api-specs#472]
I don't know how many are affected, but I discovered a few "Overview" topics that when clicked, results in 404 - Not Found.
The broken links all end with a trailing ".yml"
Removing the ".yml" from the link fixes it.

Not an exhaustive list, but here are a few examples:
- https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactsPackageTypes/Npm.yml?view=azure-devops-rest-6.1
- https://docs.microsoft.com/en-us/rest/api/azure/devops/extensionManagement/Installed%20Extensions.yml?view=azure-devops-rest-6.1
- https://docs.microsoft.com/en-us/rest/api/azure/devops/test/Code%20Coverage.yml?view=azure-devops-rest-6.1
- https://docs.microsoft.com/en-us/rest/api/azure/devops/work/Charts.yml?view=azure-devops-rest-6.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50acff83-d2a5-5da1-d933-e4ff7802933f
* Version Independent ID: 61b160a3-f418-6072-7700-b9fb1516905a
* Content: [Suite Test Case (Azure DevOps Test Plan)](https://docs.microsoft.com/en-us/rest/api/azure/devops/testPlan/Suite%20Test%20Case?view=azure-devops-rest-5.0&viewFallbackFrom=azure-devops-rest-6.1)
* Content Source: [docs-ref-autogen/5.0/testPlan/Suite Test Case.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/5.0/testPlan/Suite Test Case.yml)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by kamalhabieb** [comment]
This issue has been fixed.
https://learn.microsoft.com/en-us/rest/api/azure/devops/artifactsPackageTypes/npm?view=azure-devops-rest-6.1
https://learn.microsoft.com/en-us/rest/api/azure/devops/extensionmanagement/installed-extensions?view=azure-devops-rest-4.1&viewFallbackFrom=azure-devops-rest-6.1
https://learn.microsoft.com/en-us/rest/api/azure/devops/test/code-coverage?view=azure-devops-rest-5.0&viewFallbackFrom=azure-devops-rest-6.1
https://learn.microsoft.com/en-us/rest/api/azure/devops/work/Charts?view=azure-devops-rest-6.1
