### ISSUE TITLE
Several Overview pages in table of contents have broken URLs

### ISSUE THREAD

**Issue by zivkan** [MicrosoftDocs/vsts-rest-api-specs#474]
In the table of contents, several of the URLs are broken. For example:

* Build/Artifacts/Overview
* Build/Attachments/Overview
* Build/Builds/Overview
* Build/Timeline/Overview

While Build/Overview works, I'm guessing all the overview of the 2nd level APIs are broken, but I'm not going to check each one individually.

**Comment by kamalhabieb** [comment]
This issue has been fixed
https://learn.microsoft.com/en-us/rest/api/azure/devops/build/artifacts?view=azure-devops-rest-7.1
https://learn.microsoft.com/en-us/rest/api/azure/devops/build/attachments?view=azure-devops-rest-7.1
https://learn.microsoft.com/en-us/rest/api/azure/devops/build/builds?view=azure-devops-rest-7.1
https://learn.microsoft.com/en-us/rest/api/azure/devops/build/timeline?view=azure-devops-rest-7.1
