### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ranjan-2209** [MicrosoftDocs/vsts-rest-api-specs#477]
https://docs.microsoft.com/en-us/rest/api/azure/devops/tfvc/Branches.yml?view=azure-devops-rest-6.0 link is broken

This is `Overview` section of `Branches`

**Comment by kamalhabieb** [comment]
This issue is fixed
https://learn.microsoft.com/en-us/rest/api/azure/devops/tfvc/branches?view=azure-devops-rest-6.0
