### ISSUE TITLE
Wiki links returning '404 - Page not found' errors

### ISSUE THREAD

**Issue by Vertex-btb** [MicrosoftDocs/vsts-rest-api-specs#479]
Hello,

I've observed that many of the nav items appearing in the `[Azure DevOps Services REST API Reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1)` redirect the user to a [ '404 - Page not found' webpage](https://docs.microsoft.com/en-us/rest/api/azure/devops/testPlan/Configurations.yml?view=azure-devops-rest-6.1).   

We have not identified all of the broken pages, but it seems like a lot.  The issue occurs with many of the 'Overview' pages.

https://docs.microsoft.com/en-us/rest/api/azure/devops/testPlan/Configurations.yml?view=azure-devops-rest-6.1
https://docs.microsoft.com/en-us/rest/api/azure/devops/build/Artifacts.yml?view=azure-devops-rest-6.1
https://docs.microsoft.com/en-us/rest/api/azure/devops/work/Boardcolumns.yml?view=azure-devops-rest-6.1

Although I've provided (3) links above to demonstrate, we observe the issue is common with many of the other pages as well. 

- Brendan 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: f74b7d51-aede-ed93-437e-601654d8fa7e
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by kamalhabieb** [comment]
This issue has been fixed
