### ISSUE TITLE
Subpage - Runs/Overview gives a 404

### ISSUE THREAD

**Issue by Jandev** [MicrosoftDocs/vsts-rest-api-specs#483]
The page in the navigation menu, below this item, points to the following URL: https://docs.microsoft.com/en-us/rest/api/azure/devops/pipelines/Runs.yml?view=azure-devops-rest-6.0
There's probably something wrong with the link, as it points to a `yml` file. Omitting the extension doesn't help and also returns in a 404.

For completeness sake, this is the page I mean.
![image](https://user-images.githubusercontent.com/462356/121237187-1140ac00-c897-11eb-9d4b-d399a75df883.png)

While the Overview page is probably not used a lot, it would be great to see it fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ff7c1b-359e-b05e-f9e4-25282ecaab25
* Version Independent ID: b4f381c6-2688-8766-b7b4-cc96b2d31cf6
* Content: [Pipelines REST API for Azure DevOps Services - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/pipelines/?view=azure-devops-rest-6.0)
* Content Source: [docs-ref-conceptual/6.0/pipelines/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/6.0/pipelines/index.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **stdanie**

**Comment by Jandev** [comment]
While browsing the docs further, I see the same happening on the Releases/Overview page.
![image](https://user-images.githubusercontent.com/462356/121238369-51ecf500-c898-11eb-915c-8ec08d991626.png)

**Comment by kamalhabieb** [comment]
This issue has been fixed
