### ISSUE TITLE
Child section 'Overview' pages don't exist

### ISSUE THREAD

**Issue by flcdrg** [MicrosoftDocs/vsts-rest-api-specs#484]
The **Overview** page for every sub-section below this page don't exist and result in 404.

![image](https://user-images.githubusercontent.com/384747/121444481-c45ff100-c9ce-11eb-9784-2c3fa5f5342c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8164ec-d283-8740-236b-3a085c484008
* Version Independent ID: 06106c51-b396-9d97-9566-72e7a27375eb
* Content: [Release REST API for Azure DevOps Services - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/?view=azure-devops-rest-6.1&source=docs)
* Content Source: [docs-ref-conceptual/6.1/release/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/6.1/release/index.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by poke** [comment]
The same thing happens with apparently every section inside the “Git” category. Each overview page links to a `.yml` file when the link should be without that extension.

E.g.
- https://docs.microsoft.com/en-us/rest/api/azure/devops/git/Pull%20Requests.yml?view=azure-devops-rest-6.0
   This is the link from the navigation which results in a 404.
- https://docs.microsoft.com/en-us/rest/api/azure/devops/git/Pull%20Requests?view=azure-devops-rest-6.0
   This is the same link without the `.yml` which apparently does not exist but at least auto-redirects to the 4.1 docs.
- https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests?view=azure-devops-rest-4.1
   This is a fully working link from the 4.1 documentation.

Note that the links only break for versions *after 4.1*.

**Comment by kamalhabieb** [comment]
This issue has been fixed
