### ISSUE TITLE
Create API as documented returns 404

### ISSUE THREAD

**Issue by DarqueWarrior** [MicrosoftDocs/vsts-rest-api-specs#49]
I was trying to use the Create Work Item API call but when I do I get a 404.

PS R:\repos\vsteam&gt; Add-WorkItem -Title Test -ProjectName test -WorkItemType task -Verbose
VERBOSE: Team Module/2.1.14 (Windows) PowerShell/5.1.17134.48
VERBOSE: Body [{"op": "add", "path": "/fields/System.Title", "from": null, "value": "Test"}]
VERBOSE: POST https://tooltesterwestus2.visualstudio.com/test/_apis/wit/workitems/task?api-version=4.1 with -1-byte payload
Invoke-RestMethod :
    Page not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ebd27b9-b8ef-10fc-db9f-70026eeb27dc
* Version Independent ID: 082f3ffd-2c0e-9fdc-d52d-758de05a9557
* Content: [Work Items (VSTS Work Item Tracking)](https://docs.microsoft.com/en-us/rest/api/vsts/wit/work%20items?view=vsts-rest-4.1#feedback)
* Content Source: [docs-ref-autogen/4.1/wit/Work%20Items.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/wit/Work%20Items.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
@DarqueWarrior thanks for reporting. We're taking a look into this issue now.

**Comment by Baisakhc** [comment]
@DarqueWarrior  Can you try doing the Post with $task instead of task? So your POST url should look like :
https://tooltesterwestus2.visualstudio.com/test/_apis/wit/workitems/$task?api-version=4.1 instead of https://tooltesterwestus2.visualstudio.com/test/_apis/wit/workitems/task?api-version=4.1

**Comment by DarqueWarrior** [comment]
That fixed it. Thanks.
