### ISSUE TITLE
Variable groups overview links to a 404 error

### ISSUE THREAD

**Issue by jdholbrook81** [MicrosoftDocs/vsts-rest-api-specs#492]
https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedTask/Variablegroups.yml?view=azure-devops-rest-6.0

Link provided in the nav tree for overview displays a 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b8bb6c-ee9c-e678-cded-158c0ad31723
* Version Independent ID: 125a13e2-c2bb-0ca2-322a-66c88e695423
* Content: [Pipelines REST API for Azure DevOps Services - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/?view=azure-devops-rest-6.0)
* Content Source: [docs-ref-conceptual/6.0/distributedTask/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/6.0/distributedTask/index.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by kamalhabieb** [comment]
This issue has been fixed
https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups?view=azure-devops-rest-6.0
