### ISSUE TITLE
Issues with Overview section on multiple pages

### ISSUE THREAD

**Issue by Lddeiva** [MicrosoftDocs/vsts-rest-api-specs#494]
### Service name (the service in question)

*Task Agent* is one of the services. But, this issue is for many services.

### Description of issue (in as much detail as possible)

The overview section of many services is not accessible. 

[Pools - Overview](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedTask/Pools.yml?view=azure-devops-rest-6.0) is not accessible but [Pools - Add](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/pools/add?view=azure-devops-rest-6.0) is accessible. The overview section throws *404 - Content Not Found*.

![image](https://user-images.githubusercontent.com/61077834/126337041-34eef4b3-1c2e-4a93-8639-1a4b117b134a.png)

You can compare it with [Overview](https://docs.microsoft.com/en-us/rest/api/azure/devops/test/?view=azure-devops-rest-6.0) section of the **[Test Management](https://docs.microsoft.com/en-us/rest/api/azure/devops/test/?view=azure-devops-rest-6.0)** service.

![image](https://user-images.githubusercontent.com/61077834/126336946-d13b48ce-6179-483a-a6f3-0eb1db42bcbc.png)

**Comment by kamalhabieb** [comment]
This issue has been fixed
