### ISSUE TITLE
Batch call link

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/vsts-rest-api-specs#51]
The Batch call link seems to be missing:

https://docs.microsoft.com/en-us/rest/api/vsts/wit/batch/update.yml?view=vsts-rest-4.1
404 NOT FOUND

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aa4c957-4526-9043-cb91-5e0bee7734ea
* Version Independent ID: 450b9f73-dbbe-0f0f-c46f-079d33a92884
* Content: [Work item tracking REST API for Visual Studio Team Services (VSTS) - Visual Studio Team Services REST API](https://docs.microsoft.com/en-us/rest/api/vsts/wit/?view=vsts-rest-4.1)
* Content Source: [docs-ref-conceptual/4.1/wit/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/4.1/wit/index.md)
* Service: **vsts**
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by wnjenkin** [comment]
@jessehouwing thanks for your feedback. We're investigating this issue

**Comment by wnjenkin** [comment]
@jessehouwing the batch call api can be found here - https://docs.microsoft.com/en-us/rest/api/vsts/wit/WorkItemBatchUpdate?view=vsts-rest-4.1
