### ISSUE TITLE
Update table 'API and TFS version mapping'

### ISSUE THREAD

**Issue by michha** [MicrosoftDocs/vsts-rest-api-specs#512]
Update the table about API and TFS version:
- rename `Azure DevOps Server vNext` to `Azure DevOps Server 2020`
- update version information from `5.1` to `6.0`

There is also an other version table at https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops#supported-versions. Maybe these two tables can be joined, so there is just one point of truth 😃 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: f74b7d51-aede-ed93-437e-601654d8fa7e
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1#api-and-tfs-version-mapping)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by nechvatalp** [comment]
@michha The table has been updated, we will keep in mind to update when we release the next API version. Thank you for reporting.
