### ISSUE TITLE
VSTS REST API List Iterations does not accept 'past' or 'current' values for $timeframe

### ISSUE THREAD

**Issue by hellosnow** [MicrosoftDocs/vsts-rest-api-specs#52]
The feedback is from https://github.com/MicrosoftDocs/feedback/issues/445

Using the VSTS REST api version 4.1 AND 5.0 preview 1, making a GET request to list iterations using the $timeframe query parameter works when supplying 'current' as a timeframe value, but does not work when using 'past' or 'future' as per the documentation.

**To Reproduce**
Make a get request using the following URL (fill in appropriate values):
`https://{CompanyName}.visualstudio.com/{ProjectName}/_apis/work/teamsettings/iterations?$timeframe=past&api-version=4.1`

This returns:
```
{
    "$id": "1",
    "innerException": null,
    "message": "Specified argument was out of the range of valid values.\r\nParameter name: timeframe",
    "typeName": "System.ArgumentOutOfRangeException, mscorlib",
    "typeKey": "ArgumentOutOfRangeException",
    "errorCode": 0,
    "eventId": 0
}
```

Using either $timeframe=past or $timeframe=future reproduces the fault.
Using $timeframe=current works fine.

**Expected behaviour**
Using 'past' and 'future' as defined in the documentation here https://docs.microsoft.com/en-us/rest/api/vsts/work/iterations/list?view=vsts-rest-4.1 and https://docs.microsoft.com/en-us/rest/api/vsts/work/iterations/list?view=vsts-rest-5.0 should return a list of past and future iterations.

**Desktop (please complete the following information):**
n/a.

**Smartphone (please complete the following information):**
n/a

**Additional context**
Reproduced in Postman and C#, .Net framework 4.7.2 console application using NuGet package RestSharp v106.2.2.

**Comment by ezambra** [comment]
Hello @stuntbeaver. Thank you for reporting the issue. We've updated the documentation to mention that only $timeframe=current is supported.

**Comment by wnjenkin** [comment]
@hellosnow this issue has been resolved. The descriptions has been updated to show only current is supported.

**Comment by hellosnow** [comment]
@wnjenkin thanks for the quick fix!

**Comment by stefanstranger** [comment]
I'm getting the incorrect value returned when using current option. See attached image.
![vstscurrent](https://user-images.githubusercontent.com/2125385/42157079-0f3f6b82-7ded-11e8-9f42-60ef4f71c39c.png)

**Comment by lealcrf** [comment]
The same here. Only "current" is accepted but the timeframe attribute return is "past".

**Comment by thomasf7** [comment]
@lealcrf are you still seeing this? This looks like it was resolved in July and I am not able to reproduce it myself. If you are still seeing this it might be related to how your iterations are configured. Are you able to provide some more information on the request and response you are seeing and what you expect to see based on the current configuration you are seeing in the browser?
