### ISSUE TITLE
Failed create variable group with 401 unauthorized error

### ISSUE THREAD

**Issue by xuzhang3** [MicrosoftDocs/vsts-rest-api-specs#525]
Cannot create new variable group, failed with 401 unauthorized.
The request URL generated is: `https://dev.azure.com/<ORG>/_apis/distributedtask/variablegroups?api-version=6.0`, no project specified, if change the URL to `https://dev.azure.com/<ORG>/<projectNanme>/_apis/distributedtask/variablegroups?api-version=6.0`, the creation will success, looks like the project reference in the request body not parsed by service.

Test request body:
```json
{
    "description": "test",
    "name": "test",
    "providerData": null,
    "type": "Vsts",
    "variables": {
        "1": {
            "isSecret": false,
            "value": "1"
        },
        "2": {
            "isSecret": true,
            "value": "2"
        }
    },
    "variableGroupProjectReferences": [
        {
            "description": "test",
            "name": "postman",
            "projectReference": {
                "id": "<ProjectID>",
                "name": ""
            }
        }
    ]
}
```

Swagger: https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/distributedTask/6.0/taskAgent.json#L1142

**Comment by nechvatalp** [comment]
@xuzhang3 Hi,

I am not sure I understand the issue here. I was able to create variable group calling 

https://dev.azure.com/pnechvataltest/_apis/distributedtask/variablegroups

with 
```
{
    "description": "",
    "name": "New variable group test",
    "providerData": null,
    "type": "Vsts",
    "variables": {
        "One": {
            "isSecret": false,
            "value": "Two"
        }
    },
    "variableGroupProjectReferences": [
        {
            "description": "",
            "name": "New variable group test",
            "projectReference": {
                "id": "40bd86d1-e0fe-4699-b23d-0586d5c3489e",
                "name": ""
            }
        }
    ]
}
```
It created the variable group for the project which is in the projectReference. Is the problem that the scope vso.variablegroups_manage is not sufficient?

**Comment by xuzhang3** [comment]
@nechvatalp  this should be PAT permission issue. Ref: https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/manage-pats-with-policies-for-administrators?view=azure-devops#restrict-creation-of-full-scoped-pats

**Comment by xuzhang3** [comment]
Downgrade the API from v6 to v5 can solve the permission issue.
