### ISSUE TITLE
Unzipping an attachment fails on Windows

### ISSUE THREAD

**Issue by jenniferperez** [MicrosoftDocs/vsts-rest-api-specs#53]
Hi, I'm consuming create attachment for work item available [https://docs.microsoft.com/en-us/rest/api/vsts/wit/attachments/create?view=vsts-rest-5.0](here). I'm trying to attach a .zip file. When I go to the work item to open the attachment previously downloaded, I got "The compressed .zip folder is invalid" error message on Windows, on Linux the compressed .zip folder unzip correctly.

I clarify that when the .zip is created locally opens in both SO correctly. 

I'm using retrofit to consume the rest api like this:
`@Multipart
    @Headers("Content-Type: application/octet-stream")
    @POST("_apis/wit/attachments?api-version=5.0-preview.3")
    Call<Attachment> create(@Query("filename") String fileName, @Part MultipartBody.Part file);`

` private Attachment tryCreate(File file) throws IOException {
        RequestBody requestFile = RequestBody.create(MediaType.parse("application/octet-stream"), file);
        MultipartBody.Part body = MultipartBody.Part.create(requestFile);
        Call<Attachment> attachmentCall = service.create(file.getName(), body);
        return attachmentCall.execute().body();
    }`

Any suggestion? 
Thank you!

**Comment by paterasMSFT** [comment]
Thank you for bringing this to our attention. We are investigating the issue.

**Comment by samuelmtimbo** [comment]
Hi @jenniferperez. Thanks for reaching. Can you provide us with more details about the problem? A step-by-step way of reproducing it would be interesting. Additionally, more information about the file being uploaded could help (name, size, or the file itself, if possible). I am assuming uploading and downloading the file through the API happen successfully, but the downloaded file seems to be corrupted when trying to open it on Windows.

**Comment by jenniferperez** [comment]
Hi, yes, your assumption is correct. The file size changes because it is created by a Framework and contains tests execution results. I must say that if I change the extension from .zip to .rar it works correctly.

Step by step:
1. I create a .zip file (now .rar)
2. I call create attachment using this  url:  https://{accountName}.visualstudio.com/{project}/_apis/wit/attachments?api-version=5.0-preview.3 usinf POST method and sending the .zip as body with octet-stream content type.
3. The create attachment service returns a url where attachment is located. When I hit it the download starts and if I open it on Windows an error is raised.I attach an example file.

[attachment (6).zip](https://github.com/MicrosoftDocs/vsts-rest-api-specs/files/2192939/attachment.6.zip)

**Comment by samuelmtimbo** [comment]
Could you send us the exact .zip file sent to the server and the one retrieved later? I am assuming the "attachment (6).zip" file is the one you retrieved later. Also, why are you trying to upload the file as a `MultipartBody`?
