### ISSUE TITLE
Configurations List Api is broken?

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/vsts-rest-api-specs#54]
The issue was created by @arsunda from https://github.com/MicrosoftDocs/feedback/issues/302

Idea Title
Be as descriptive as you can with your idea/bug report/question/suggestion.
Issue Details
When using the api specified here , the list api works fine. However, when specifying any scope parameters using the format specified in the page, the value returned is always an empty list
{ "count": 0, "value": [] }
When i have no scope specified, I get a list of policies which have this field
eg: "scope": [ { "refName": "refs/heads/master", "matchKind": "Exact", "repositoryId": "{repo-id}" } ]
Using the refName or the repository id with wildcards, or using them both to specify the scope always returns the empty value as above. Using the policy parameter works fine
Has anything changes with regards to how this api is documents/set up???

**Comment by Powerhelmsman** [comment]
@wnjenkin Transferred the issue as you required.

**Comment by hross** [comment]
This parameter is actually a very confusing legacy implementation. We do not recommend you use it, as it will probably not do what you want (as you are discovering 😄) but we keep it for legacy support purposes. If you look at [this policy API](https://docs.microsoft.com/en-us/rest/api/vsts/git/policy%20configurations/list?view=vsts-rest-5.0) you can query for all policies on a given ref/repository.

**Comment by wnjenkin** [comment]
@arsunda
