### ISSUE TITLE
Version is examples is incorrect

### ISSUE THREAD

**Issue by MikeBarker-MSFT** [MicrosoftDocs/vsts-rest-api-specs#540]
This documentation is listed under 7.1-preview but examples are shown using version 6.1-preview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff22a24-a423-d794-2d80-9256298e1eaa
* Version Independent ID: 4782ca92-bfc8-abeb-8f7b-98578d8e88e8
* Content: [Token Lifecycle Management REST API for Azure DevOps Services - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/tokens/?view=azure-devops-rest-7.1&tabs=powershell&viewFallbackFrom=azure-devops-rest-7.0)
* Content Source: [docs-ref-conceptual/7.1/tokens/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/7.1/tokens/index.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **sergiikozak**

**Comment by kamalhabieb** [comment]
Thank you for reporting this issue, the example has now been fixed to take the latest version.
