### ISSUE TITLE
Typo Cloud Load Test overview

### ISSUE THREAD

**Issue by shblue21** [MicrosoftDocs/vsts-rest-api-specs#545]
[Enter feedback here]
typo ####Notes -> ### Notes

![image](https://user-images.githubusercontent.com/25363091/170683315-8a41b661-a5b0-4b50-ae5c-7da9719427c5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b221c6-613b-f670-144b-e658b82b9d77
* Version Independent ID: 74f443e6-d135-f37a-4653-edd59781be95
* Content: [Cloud load test REST API for Azure DevOps Services - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/clt/?view=azure-devops-rest-7.1#feedback)
* Content Source: [docs-ref-conceptual/7.1/clt/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/7.1/clt/index.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **kaelli**

**Comment by nechvatalp** [comment]
@shblue21 Thanks for reporting Cloud Load Test has been decommisioned some time ago so we completely removed the CLT documentation section.
