### ISSUE TITLE
ends a bit prematurely 

### ISSUE THREAD

**Issue by ActualReverend** [MicrosoftDocs/vsts-rest-api-specs#548]
The info ends with : 
" If there are more than one, then it is ... "

I have no idea if this sentence is longer somewhere, or is supposed to link somewhere else?  Seems like it ends a bit too quickly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32098e26-5459-9fa6-0b88-92efa931db59
* Version Independent ID: a42e6a21-a97f-a0e7-7468-4603b4812fcd
* Content: [Status - REST API (Azure DevOps Build)](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/status?view=azure-devops-server-rest-6.0)
* Content Source: [docs-ref-autogen/azure-devops-server-6.0/build/Status.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/azure-devops-server-6.0/build/Status.yml)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by kamalhabieb** [comment]
Thank you @ActualReverend  for reporting this issue.
It has been resolved https://learn.microsoft.com/en-us/rest/api/azure/devops/build/status/get?view=azure-devops-rest-7.1
