### ISSUE TITLE
Regarding getting TFS WorkItems using Ids

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/vsts-rest-api-specs#55]
This issue was created by @sangam-sgm from https://github.com/MicrosoftDocs/feedback/issues/299. 
Regarding getting TFS WorkItems using Ids
I was using rest api for tfs to get workitems details by ids but when i am giving all the ids the api is turning to be very large and hence its not processing and returning internal server error message.
My concern is that can you people make this api as post request as well so that i can pass as many ids as we can.

The doc link i used to get the api is https://docs.microsoft.com/en-us/rest/api/vsts/wit/work%20items/list
In the api GET https://{accountName}.visualstudio.com/{project}/_apis/wit/workitems?ids={ids}&api-version=4.1-preview if i am giving lots of ids comma seperated then its failing because of url length.

**Comment by Powerhelmsman** [comment]
@wnjenkin Transferred the issue as you required.

**Comment by Baisakhc** [comment]
Yes, the getworkitems with large number of ids can reach the maximum json limit and throws error. We do have plans for getworkitems as a POST to support bigger scale of input ids but not available today. For now, as a workaround, can you try breaking up your invocation in two(or more, depending on the number of ids you have) GetWOrkItems with the ids divided between them to get results from getworkitems.

**Comment by wnjenkin** [comment]
@sangam-sgm does the answer provided by @Baisakhc help?
