### ISSUE TITLE
404 error in a linked page

### ISSUE THREAD

**Issue by michha** [MicrosoftDocs/vsts-rest-api-specs#559]
It says _Look up the [documentation](https://docs.microsoft.com/en-us/vsts/search/overview) to learn more_ but this link is not valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a2ad993-c879-8128-fc56-3523b33eaef3
* Version Independent ID: 85b08da1-23de-388d-b08d-5aefa587cc48
* Content: [Search REST API for Azure DevOps Services - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/search/?view=azure-devops-rest-7.1)
* Content Source: [docs-ref-conceptual/7.1/search/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/7.1/search/index.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **pnechvatal**

**Comment by kamalhabieb** [comment]
This issue has been fixed
