### ISSUE TITLE
CreateOrUpdate Snapshot REST API - No mention of how to specify that the disk is a managed disk

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/vsts-rest-api-specs#56]
This issue was created by @meetamitbhatia from https://github.com/MicrosoftDocs/feedback/issues/273
The REST API documentation for creating disk snapshots can be found at https://docs.microsoft.com/en-us/rest/api/compute/snapshots/createorupdate. It makes no mention of how to specify that the disk is a managed disk.

**Comment by Powerhelmsman** [comment]
@wnjenkin Transferred the issue as you required.

**Comment by wnjenkin** [comment]
Issue transferred to Azure - https://github.com/MicrosoftDocs/azure-docs/issues/11163
