### ISSUE TITLE
Documentation link goes to 404.

### ISSUE THREAD

**Issue by aaronrogers** [MicrosoftDocs/vsts-rest-api-specs#562]
First paragraph states:
> Look up the [documentation](https://docs.microsoft.com/en-us/vsts/search/overview)...

The link sends the user to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a2ad993-c879-8128-fc56-3523b33eaef3
* Version Independent ID: 85b08da1-23de-388d-b08d-5aefa587cc48
* Content: [Search REST API for Azure DevOps Services - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/search/?view=azure-devops-rest-7.1)
* Content Source: [docs-ref-conceptual/7.1/search/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/7.1/search/index.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **pnechvatal**

**Comment by kamalhabieb** [comment]
https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/555

**Comment by kamalhabieb** [comment]
Thank you @aaronrogers for reporting this issue, I have directed it to the responsible team, and they will fix it soon.

**Comment by nechvatalp** [comment]
Closing as duplicate
