### ISSUE TITLE
Add ASP.NET MVC and WebAPI API reference 

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/vsts-rest-api-specs#57]
This issue was from https://github.com/MicrosoftDocs/feedback/issues/90
The API reference for MVC and WebAPI is still only available on MSDN, not on the "docs" site.
https://docs.microsoft.com/en-us/aspnet/api-ref
Ideally, they should also be integrated into the API Browser.

⚠ Idea migrated from UserVoice
Created By: Richard
Created On: 2017/11/20 15:51:06 +0000
Votes at Migration: 2
Supporters at Migration: 2

**Comment by Powerhelmsman** [comment]
@wnjenkin Transferred the issue as you required.

**Comment by dend** [comment]
@Powerhelmsman this is not REST. This is a request to onboard .NET APIs. 😀
