### ISSUE TITLE
PATs List API - "requested operation is not allowed"

### ISSUE THREAD

**Issue by jdholbrook81** [MicrosoftDocs/vsts-rest-api-specs#571]
Tried calling the api documented here: https://learn.microsoft.com/en-us/rest/api/azure/devops/tokens/pats/list?view=azure-devops-rest-7.1&tabs=HTTP

Passed no additional parameters, received response:

{
  "$id": "1",
  "innerException": null,
  "message": "The requested operation is not allowed.",
  "typeName": "Microsoft.TeamFoundation.Framework.Server.InvalidAccessException, Microsoft.TeamFoundation.Framework.Server",
  "typeKey": "InvalidAccessException",
  "errorCode": 0,
  "eventId": 3000
}

Also, there is no link to provide feedback at the bottom of the PAT List documentation so I had to go to the parent document (Tokens).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff22a24-a423-d794-2d80-9256298e1eaa
* Version Independent ID: 4782ca92-bfc8-abeb-8f7b-98578d8e88e8
* Content: [Token Lifecycle Management REST API for Azure DevOps Services - Azure DevOps Services REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/tokens/?view=azure-devops-rest-7.1&tabs=powershell)
* Content Source: [docs-ref-conceptual/7.1/tokens/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/7.1/tokens/index.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **sergiikozak**

**Comment by nechvatalp** [comment]
You need to use AAD token to access this API it is mentioned in the overview
[Personal Access Tokens](https://learn.microsoft.com/en-us/rest/api/azure/devops/tokens/?view=azure-devops-rest-7.1&tabs=powershell#personal-access-tokens-pats)
