### ISSUE TITLE
API and TFS version mapping table is missing Azure DevOps Server 2022

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/vsts-rest-api-specs#592]
"API and TFS version mapping" table is missing the latest **Azure DevOps Server 2022**.

Please add **Azure DevOps Server 2022** to the list with its corresponding API version.

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: f74b7d51-aede-ed93-437e-601654d8fa7e
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-7.1&WT.mc_id=DOP-MVP-21138)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by nechvatalp** [comment]
Thanks for reporting mapping has been added.
