### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.devops.v7_1.git.git_client'

### ISSUE THREAD

**Issue by avivtabak** [MicrosoftDocs/vsts-rest-api-specs#597]
There is an error when calling git_client in Python SDK version 7.1.0b1

```
from azure.devops.connection import Connection
connection = Connection(base_url=org_url, creds=credentials)
git_client = self.connection.clients_v7_1.get_git_client()
```

This will raise an exception because the imports are wrong in `client_factory.py`:

`    def get_git_client(self):
        """get_git_client.
        Gets the 7.1 version of the GitClient
        :rtype: :class:`<GitClient> <azure.devops.v7_1.git.git_client.GitClient>`
        """
        return self._connection.get_client('azure.devops.v7_1.git.git_client.GitClient')
`

Suggestion for correction:
`       
 return self._connection.get_client('azure.devops.v7_1.git.git_client_base.GitClientBase')
`

also inazure/devops/v7_1/git/__init__.py:11
you need to change from:
`from .git_client import GitClient`
to
`from .git_client_base import GitClientBase`

thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9043a81-eba3-f582-2560-87651cf3c34c
* Version Independent ID: f0e8be98-093a-6d23-cef7-2d4da8f1fd67
* Content: [Git REST API for Azure DevOps Services - Azure DevOps Services REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/?view=azure-devops-rest-7.1)
* Content Source: [docs-ref-conceptual/7.1/git/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/7.1/git/index.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **pnechvatal**

**Comment by nechvatalp** [comment]
Hello, thanks for reporting, this issue should be resolved in newer versions of the Python SDK. Best place to report such issues would be on the repository for python sdk https://github.com/microsoft/azure-devops-python-api
