### ISSUE TITLE
Members Rest API ContinuationToken returned as string 'Microsoft.IdentityModel.Claims.ClaimsIdentity;<NUMBER>@Live.com'

### ISSUE THREAD

**Issue by JaDevGuy** [MicrosoftDocs/vsts-rest-api-specs#60]
When calling the below API uri it returns the continuationtoken as a string 'Microsoft.IdentityModel.Claims.ClaimsIdentity;<NUMBER>@Live.com'

https://{account}.vsaex.visualstudio.com/_apis/GroupEntitlements/{groupOriginId}/members?maxResults=2&api-version=4.1-preview.1

Please note I am testing with maxResults set to 2 in order to force paging so my script will be able to handle the scenario properly.

Please let me know if there is anything else you need to troubleshoot this.

**Comment by lorenpaulsen** [comment]
The continuation token should be the subject descriptor of the last user from the previous batch, so this looks normal. Is paging not working for you?
