### ISSUE TITLE
PUT and POST PAT permissions

### ISSUE THREAD

**Issue by giwleb** [MicrosoftDocs/vsts-rest-api-specs#601]
Noticed that is is not very clear what Persaonal Access Token permissions are needed for PUT and POST (Add and Update). I tried, with Update, the Variable Groups "read & create" permission level for these, but that still gives a 401 Unauthorized.

The document mentions "Basic", not not sure what this means in terms of PAT scopes.

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78f95eb7-e287-f094-a350-0330aeb8b186
* Version Independent ID: 69794bed-6f92-5047-d4d3-2dee24f6af6a
* Content: [Variablegroups - REST API (Azure DevOps Distributed Task)](https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups?view=azure-devops-rest-7.0)
* Content Source: [docs-ref-autogen/7.0/distributedTask/Variablegroups.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/7.0/distributedTask/Variablegroups.yml)
* Service: **azure-devops**
* Sub-service: **azure-devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by giwleb** [comment]
I've learned that, at least for PUT, the permissions needed are Read, create, & manage.

**Comment by nechvatalp** [comment]
Hi, @giwleb I would recommend checking out the latest preview version of the documentation it is most up-to-date and it looks like it contains which scopes are needed for which operation.
https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups/add?view=azure-devops-rest-7.1#oauth2
