### ISSUE TITLE
What are the security scope(s) needed for using these REST functions?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-rest-api-specs#607]
Guessing its probably at least "Workitem Read".  Is this info documented somewhere else?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21f222a3-2519-88f9-d05a-852790d420a8
* Version Independent ID: 4cba102e-f6ff-f2ae-57b5-18a0501d99c0
* Content: [Queries - REST API (Azure DevOps Work Item Tracking)](https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/queries?view=azure-devops-rest-7.0)
* Content Source: [docs-ref-autogen/7.0/wit/Queries.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/7.0/wit/Queries.yml)
* Service: **azure-devops**
* Sub-service: **azure-devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by nechvatalp** [comment]
Hi @StingyJack yes we document scopes, each API should have scopes it requires documented in a Scopes section.

For the create queries for example that would be here https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/queries/create?view=azure-devops-rest-7.0&tabs=HTTP#scopes
