### ISSUE TITLE
Well-known policy type ID list

### ISSUE THREAD

**Issue by mot256** [MicrosoftDocs/vsts-rest-api-specs#613]
Should this page (or wherever it is appropriate) have a list of well-known types?
e.g. Should we just assume the type ID for a build confirmation policy is a constant 0609b952-1397-4640-95ec-e00a01b2c241 (as inferred from this [example](https://learn.microsoft.com/en-us/rest/api/azure/devops/policy/configurations/create?view=azure-devops-rest-5.0&tabs=HTTP#build-policy))?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8698d643-1672-3520-3af4-8d753898292b
* Version Independent ID: a4443f4d-68d1-2047-60cb-e5c835c2be65
* Content: [Types - REST API (Azure DevOps Policy)](https://learn.microsoft.com/en-us/rest/api/azure/devops/policy/types?view=azure-devops-rest-5.0)
* Content Source: [docs-ref-autogen/5.0/policy/Types.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/5.0/policy/Types.yml)
* Service: **azure-devops**
* Sub-service: **azure-devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by nechvatalp** [comment]
The query types is to all the types and using it you will always have up-to-date. It is safe to assume that the type ids won't change so 0609b952-1397-4640-95ec-e00a01b2c241 will always be the policytype id.
