### ISSUE TITLE
Examples missing

### ISSUE THREAD

**Issue by jrmartin0723** [MicrosoftDocs/vsts-rest-api-specs#615]
The page says that there should be an example for using the batch endpoint for adding attachments, but there are no examples provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9d8bd99-f62b-c907-350f-3b16d5880755
* Version Independent ID: 8000e858-6f0f-e139-8dfb-64f2f06e762e
* Content: [Work item Batch Updates - Azure DevOps Services REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/workitembatchupdate?view=azure-devops-rest-7.0)
* Content Source: [docs-ref-conceptual/7.0/wit/WorkItemBatchUpdate.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/7.0/wit/WorkItemBatchUpdate.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by nechvatalp** [comment]
This was fixed in the newer docmentation versions [Work Item Batch Update Api](https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/?view=azure-devops-rest-7.2#work-item-batch-update-api-)
