### ISSUE TITLE
Documentation Sparse

### ISSUE THREAD

**Issue by coderangerdan** [MicrosoftDocs/vsts-rest-api-specs#62]
The documentation is next to useless, there is no description as to what each of these APIs do and why you might need them

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fdce00f-8d63-9ac8-67da-cd49b59d6fa2
* Version Independent ID: e570fafd-41a8-f758-01cf-26cf8ee3fc8e
* Content: [Releases (VSTS Release)](https://docs.microsoft.com/en-us/rest/api/vsts/release/releases?view=vsts-rest-5.0)
* Content Source: [docs-ref-autogen/5.0/release/Releases.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/5.0/release/Releases.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by shashban** [comment]
Can you please point us to the specific API for which you are finding the description missing?
