### ISSUE TITLE
All examples at rest/api/vsts/git/pull%20requests/get%20pull%20requests look the same

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/vsts-rest-api-specs#63]
This issue was created by @kiewic from https://github.com/MicrosoftDocs/feedback/issues/343. 
The three examples in the VSTS Pull Requests REST API look the same
The three examples look like this:

Issue Details
I think the Sample Requests should be different to accomplish the different examples:
Just completed pull requests
Pull requests by repository
Targeting a specific branch
Though I do not know if the query parameters are supposed to be passed in the query string or as a request payload.
Thanks!

**Comment by tedchamb** [comment]
Thanks for reporting @Powerhelmsman .  All query parameters on this doc site should be sent in the query string and not the body.  The links for the examples are missing them.  I will follow up with the team that owns these to get them fixed.

**Comment by tedchamb** [comment]
This has been fixed.
