### ISSUE TITLE
Unclear where to find example payload for adding a work item link

### ISSUE THREAD

**Issue by ostreifel** [MicrosoftDocs/vsts-rest-api-specs#64]
For the work item tracking rest apis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaeeaf88-2b70-c9ac-44a5-5433f38fe2de
* Version Independent ID: ae1cba6f-cacb-b459-86e7-bcd36592c796
* Content: [Artifact Link Types (VSTS Work Item Tracking)](https://docs.microsoft.com/en-us/rest/api/vsts/wit/artifact%20link%20types?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/wit/Artifact%20Link%20Types.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/wit/Artifact%20Link%20Types.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by micarls** [comment]
The documentation is in the "Work Items -> Update" section.

Direct link is here: https://docs.microsoft.com/en-us/rest/api/vsts/wit/work%20items/update?view=vsts-rest-4.1#add_a_link
