### ISSUE TITLE
params missing in GET uri

### ISSUE THREAD

**Issue by elbatk** [MicrosoftDocs/vsts-rest-api-specs#65]
Created originally on [vsts-docs here](https://github.com/MicrosoftDocs/vsts-docs/issues/1287#event-1730969814)

The GET of a list of approvals does not show all request parameters, almost all query params are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 664c74de-5612-9eb4-06f8-dc95c304c2fe
* Version Independent ID: ff6be0b3-1619-7813-27c4-58d00094f9e9
* Content: [Release approvals](https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/rm/approvals?view=vsts)
* Content Source: [docs/integrate/previous-apis/rm/approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/rm/approvals.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by wnjenkin** [comment]
@shashban to follow up here

**Comment by wnjenkin** [comment]
@A-AontwSR it looks like you are using a previous version of our Rest Api docs. Have you tried looking here to see our newer versions - https://docs.microsoft.com/en-us/rest/api/vsts/release/approvals/list?view=vsts-rest-4.1 ?

**Comment by A-AontwSR** [comment]
@wnjenkin Yes, I know that the newer API version is also documented. But as a TFS on-prem user I'm more interested in the documentation of the older API.

**Comment by shashban** [comment]
@A-Aontwsr  : Can you share what specific parameter are you finding as missed? As this is documentation for an older version, we'll get it verified for compatability.
