### ISSUE TITLE
VSTS Rest API 4.1 - Targets - Update

### ISSUE THREAD

**Issue by Dejulia489** [MicrosoftDocs/vsts-rest-api-specs#66]
The parameter 'machinesToUpdate' is not defined in the documentation. 

Error: 
"Value cannot be null.\r\nParameter name: machinesToUpdate"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93bebca-d736-63ea-fb96-847a401155d0
* Version Independent ID: 0a3037bb-ea83-8a46-64a4-e69ed65671a1
* Content: [Targets (VSTS Task Agent)](https://docs.microsoft.com/en-us/rest/api/vsts/distributedtask/targets?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/distributedTask/Targets.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/distributedTask/Targets.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
@chrisrpatterson to take a look into this

**Comment by chrisrpatterson** [comment]
@RoopeshNair for deploymentgroups

**Comment by RoopeshNair** [comment]
This is mostly because the PATCH body is probably wrong here. Can you please refer to this and try again?
https://docs.microsoft.com/en-us/rest/api/vsts/distributedtask/targets/update?view=vsts-rest-4.1

If it is still not working, share the PATCH body

**Comment by wnjenkin** [comment]
@Dejulia489 does this help resolve the issue

**Comment by Dejulia489** [comment]
@RoopeshNair, 
Thank you for looking into this, that is the documentation that I was referring to. It is missing any reference to the 'MachinesToUpdate'. 

The issue persists if you do not specify all targets in the group. The below will fail because there are actually 3 targets in that group. 

Invoke: 
{
    "ContentType":  "application/json",
    "Method":  "PATCH",
    "Body":  "{
        "tags":  [
            "MyTag",
            "DV1"
],
    "id":  7587
}",
    "UseDefaultCredentials":  true,
    "Uri":  "https://%TFSURI%/%ProjectCollection%/TaskRunner/_apis/distributedtask/deploymentgroups/755/targets?api-version=4.1-preview.1"
}

**Comment by arjgupta** [comment]
@Dejulia489 , the body should be an array of targets, see the documentation. Wrap the body around square brackets.
