### ISSUE TITLE
Not Supported in TFS 2018 Update 2

### ISSUE THREAD

**Issue by sblasko4868** [MicrosoftDocs/vsts-rest-api-specs#73]
I am running TFS 2018 Update 2 and the "Backlogs" endpoints return 404s. Where can I find the documentation for the latest supported API for TFS 2018?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955793d0-78ad-71dc-67b3-bc4512d753eb
* Version Independent ID: 3aee00f8-d30d-cf8e-c7e4-e17031d67f52
* Content: [Backlogs (VSTS Work)](https://docs.microsoft.com/en-us/rest/api/vsts/work/backlogs?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/work/Backlogs.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/work/Backlogs.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by nschonni** [comment]
Anything but VSTS seems to be under https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/overview?view=tfs-2018
