### ISSUE TITLE
Arrays are wrapped

### ISSUE THREAD

**Issue by froens** [MicrosoftDocs/vsts-rest-api-specs#74]
All returned arrays (e.g. from list-method) are wrapped in a wrapper-object containing a count-property (containing length of array) and value (containing the array)

**Example**
The documentation states that the updates-API List-method:
` /{project}/_apis/wit/workItems/{id}/updates)`
 returns: 
`WorkWorkItemUpdate[]`

In fact the API returns the value in a wrapper-object:
```
{
   "count": number,
   "value": WorkItemUpdate[]
}
```

I have generated a client using Swagger-CodeGen. The client fails, since it expects the array at the root of the response.

**Comment by ndagrawal** [comment]
@froens Would you please share the link to the documentation you are referring to? 

Both the 4.1 and 5.0 version of rest APIs for getting work-item updates give count and value : (list of updates) in the response.
https://docs.microsoft.com/en-us/rest/api/vsts/wit/updates/list?view=vsts-rest-5.0
https://docs.microsoft.com/en-us/rest/api/vsts/wit/updates/list?view=vsts-rest-4.1

Please share those links.

**Comment by ndagrawal** [comment]
Hi @froens,

That's the pattern we follow through all our rest APIs, which return the list of objects. We return a wrapper object, with its count, and all the list of expected objects. 

You will have to tweak the code generation tool accordingly.

**Comment by pabrams** [comment]
The documentation still states it's an array, but according to Froen's example, it's not.  To me it doesn't look like Froen is asking how to do it - looks like he already figured that out.  I think he's just trying to report the inconsistency in the documentation, which states that an array will be returned.

**Comment by froens** [comment]
@pabrams 
Your assumptions are correct: The problem is exactly that the swagger-documentation is incorrect when compared to the actual returned objects.

@ndagrawal there is a mismatch between your pattern and the documentation.
