### ISSUE TITLE
Typo in "Get" operation description

### ISSUE THREAD

**Issue by gmahender** [MicrosoftDocs/vsts-rest-api-specs#75]
"Retuens" instead of "Returns"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3400e84-6653-9042-0eb3-13787f7ecbf2
* Version Independent ID: 6c723c5f-2ccb-421f-9e0e-a111f54f000c
* Content: [Work Item Types Fields (VSTS Work Item Tracking Process Definitions)](https://docs.microsoft.com/en-us/rest/api/vsts/processdefinitions/work%20item%20types%20fields?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/processDefinitions/Work%20Item%20Types%20Fields.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/processDefinitions/Work%20Item%20Types%20Fields.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
@gmahender thanks for reporting this. Working on a fix to update the spelling here
