### ISSUE TITLE
Items list with "fileName" parameter - not working

### ISSUE THREAD

**Issue by chrisbarton126** [MicrosoftDocs/vsts-rest-api-specs#76]
When accessing the below URL, I would expect to only receive results whereby the filename is either Default.aspx or partially matches the value provided, however, I still receive all files in the root directory as well as all folders. 

https://{account}.visualstudio.com/{project}/_apis/tfvc/items?api-version=4.1&fileName=Default.aspx

Also, the documentation states that the values for the recursionLevel parameter are all camel case, however, if you try this then you get an error response indicating otherwise. 

Thanks.

**Comment by BrLawl** [comment]
Hi Chris, the URL is missing the path query parameter which is required under the specification for this call.
