### ISSUE TITLE
VSTS Rest API 4.1 - Targets - Get

### ISSUE THREAD

**Issue by Dejulia489** [MicrosoftDocs/vsts-rest-api-specs#77]
Unable to get a deployment group's targets unless they have been tagged at the team project level. 

ContentType:                    
application/json
Method:                      
GET
Uri:                            https://tfs.ld.corp.local/Devops/TaskRunner/_apis/distributedtask/deploymentgroups/755?api-version=4.1-preview.1

Returns:
machines     : {}
machineCount : 0
id           : 755
project      : @{id=5b13e75b-ae22-445b-9841-4ec15a60d1a2; name=TaskRunner}
name         : DV1
pool         : @{id=61; scope=d1e56559-884e-4bdb-97f9-5971bdeb71c6; name=DV1; isHosted=False; poolType=deployment; size=14}

![image](https://user-images.githubusercontent.com/24240426/43925644-a26eeccc-9bdc-11e8-83eb-bf9d79385ad7.png)

Once I tag a target it will return 

ContentType:                    
application/json
Method:                      
GET
Uri:                            https://tfs.ld.corp.local/Devops/TaskRunner/_apis/distributedtask/deploymentgroups/755?api-version=4.1-preview.1

Returns:
machines     : {@{tags=System.Object[]; id=229; agent=}}
machineCount : 0
id           : 755
project      : @{id=5b13e75b-ae22-445b-9841-4ec15a60d1a2; name=TaskRunner}
name         : DV1
pool         : @{id=61; scope=d1e56559-884e-4bdb-97f9-5971bdeb71c6; name=DV1; isHosted=False; poolType=deployment; size=14}

![image](https://user-images.githubusercontent.com/24240426/43925712-e01838f8-9bdc-11e8-8234-1bd2f357007e.png)

**Comment by Dejulia489** [comment]
This may be the wrong repo for this bug, it does not pertain to the documentation itself but rather the functionality of the API. Please point me to the right repo if that is the case. 

Thanks

**Comment by nschonni** [comment]
If it's a bug, it would probably be better posted to https://developercommunity.visualstudio.com/spaces/22/index.html

**Comment by wnjenkin** [comment]
@Dejulia489 are you still experiencing this issue?

**Comment by Dejulia489** [comment]
@wnjenkin I have opened a ticket within the development community as suggested. 

https://developercommunity.visualstudio.com/content/problem/337887/vsts-rest-api-41-targets-get.html
