### ISSUE TITLE
rest/api/vsts/search/?view=vsts-rest-4.1 results in 302 errors

### ISSUE THREAD

**Issue by wavemotionio** [MicrosoftDocs/vsts-rest-api-specs#79]
The new search endpoints are not working correctly.  All others are.  Why would this be?

POST https://{accountName}.almsearch.visualstudio.com/{project}/_apis/search/codesearchresults?api-version=4.1-preview.1

POST https://{accountName}.almsearch.visualstudio.com/{project}/_apis/search/workitemsearchresults?api-version=4.1-preview.1

POST https://{accountName}.almsearch.visualstudio.com/{project}/_apis/search/wikisearchresults?api-version=4.1-preview.1

302 errors in Restlet Client, Browser, and Node.js.  Any ideas why only these three endpoints wouldn't be working correctly?

Other 4.1-preview.1 endpoints seem to work fine.

Thanks!

**Comment by wavemotionio** [comment]
Note: using PAT authentication

**Comment by wavemotionio** [comment]
[POST]
{
  "searchText": "CodeSearchController",
  "$skip": 0,
  "$top": 1,
  "includeFacets": true
}

**Comment by wnjenkin** [comment]
@wavemotionio thanks for the feedback. Taking a look into this

**Comment by ShilpiRachna** [comment]
@wavemotionio ,

What Authorization scopes are you using for accessing these endpoints?
Can you please try with the authorization scopes as specified below:

1. For code search _i.e. POST https://{accountName}.almsearch.visualstudio.com/{project}/_apis/search/codesearchresults?api-version=4.1-preview.1_, the authorization scope should be Code (read),  Code (read and write),
 Code (read, write, and manage) or Code (full)

2. For work item search _i.e. POST https://{accountName}.almsearch.visualstudio.com/{project}/_apis/search/workitemsearchresults?api-version=4.1-preview.1_, the authroization scope should be Work items (read), Work items (read and write) or Work items (full).

3. For wiki search _i.e. POST https://{accountName}.almsearch.visualstudio.com/{project}/_apis/search/wikisearchresults?api-version=4.1-preview.1_, the authorization scope should be Wiki (read) or Wiki (read and write)

Please get back if you continue to face any issue.

Thanks!
Shilpi Rachna
