### ISSUE TITLE
"All API versions will work on the server version mentioned as well as later versions."

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-rest-api-specs#84]
Where does TFS 2015 Update 4 fit into this list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: 34a63078-bfe5-7cb5-e278-bf9edaa3fa4d
* Content: [Get started with the REST APIs for Visual Studio Team Services and Team Foundation Server - Visual Studio Team Services REST API](https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by wnjenkin** [comment]
@StingyJack TFS 2015 Update 4 supports api version 2.3. We'll get the docs updated to reflect this. Thanks for pointing this out
