### ISSUE TITLE
Mutual Certificate SSL support for VSTS (Azure DevOps)

### ISSUE THREAD

**Issue by dguimbellot** [MicrosoftDocs/vsts-rest-api-specs#86]
We build an externally hosted SaaS that interacts with the VSTS REST API. 

how do we enable mutual certificate TLS (two way SSL) for VSTS? 

Our customers are concerned that a single tier Authentication is potentially susceptible to a range of attacks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: 34a63078-bfe5-7cb5-e278-bf9edaa3fa4d
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1&viewFallbackFrom=vsts)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by wnjenkin** [comment]
@justmarks to help with this issue

**Comment by justmarks** [comment]
Azure DevOps does not support Certificate auth today.  To be honest, we haven't heard a lot of requests for this so it's not likely to move up the backlog

**Comment by dguimbellot** [comment]
i guess we wait for the first hack...
