### ISSUE TITLE
Where to report bugs to the .NET clients? Where to find sourcecode?

### ISSUE THREAD

**Issue by Sl1ckR1ck** [MicrosoftDocs/vsts-rest-api-specs#90]
Hi,

i am trying to find where i can report a bug for the .NET wrappers of the API.

I think i found a bug in the UpdateReleaseDefinitionAsync of the Microsoft.VisualStudio.Services.ReleaseManagement.WebApi.dll.

But i dont know where to report it? Also i would like to see the source code of it to see if i am misusing it?

Any help would be appreciated.

**Comment by wnjenkin** [comment]
@Sl1ckR1ck .Net client libraries can be found here - https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=vsts . There is also a link to a location to provide feedback on this page
