### ISSUE TITLE
Difference between Get Commits Batch and Get Commits

### ISSUE THREAD

**Issue by mmajcica** [MicrosoftDocs/vsts-rest-api-specs#91]
As stated in the title, I'm looking for a difference in between. Aside of a different way of passing in the search criteria, they both return GitCommitRef model. So I would like to know when to use one or the other? Are there any performance differences in between the two?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0072a55f-5438-d0bd-ac6a-1810acbbd653
* Version Independent ID: 60f1c450-26f8-4619-2fa8-3eb37d62d620
* Content: [Commits (VSTS Git)](https://docs.microsoft.com/en-us/rest/api/vsts/git/commits?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/git/Commits.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/git/Commits.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by alepauly** [comment]
The main difference is that using GetCommitsBatch (POST with criteria in body) will allow you to provide an arbitrarily large list of commit Id's to retrieve. GetCommits can do similar but only as much as you can fit in the url as query parameters. Functionally, the only difference is that GetCommitsBatch allows you to get statuses linked to commits (using includeStatuses query param), which cannot be done with GetCommits.
