### ISSUE TITLE
'work item tracking' broken link

### ISSUE THREAD

**Issue by ranjan-ranjan** [MicrosoftDocs/vsts-rest-api-specs#98]
'work item tracking' broken link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: 34a63078-bfe5-7cb5-e278-bf9edaa3fa4d
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1#client-libraries)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Thanks @ranjan-ranjan , fixing this issue and a few other broken links on the same page!
