### ISSUE TITLE
Limit of 50 characters in searchText when using isExactName on listing release definitions

### ISSUE THREAD

**Issue by brianpcurran** [MicrosoftDocs/vsts-rest-api-specs#99]
I'm using the API endpoint that lists release definitions: https://docs.microsoft.com/en-us/rest/api/vsts/release/definitions/list?view=vsts-rest-4.1

I created a release definition to test this and named it `New release pipeline (1) Testing 50-character Limi` (50 characters long including spaces).

When I send a request to `https://vsrm.dev.azure.com/<org>/<project>/_apis/release/definitions?api-version=4.1-preview.3&searchText=New release pipeline (1) Testing 50-character Limi&isExactNameMatch=true` it returns a release definition just fine.

I renamed the release definition to `New release pipeline (1) Testing 50-character Limit` (51 characters) and tried the same request, with the new name as `searchText`: `https://vsrm.dev.azure.com/<org>/<project>/_apis/release/definitions?api-version=4.1-preview.3&searchText=New release pipeline (1) Testing 50-character Limit&isExactNameMatch=true` and the API does not return anything.

If I remove the `isExactNameMatch` parameter and send a request to `https://vsrm.dev.azure.com/<org>/<project>/_apis/release/definitions?api-version=4.1-preview.3&searchText=New release pipeline (1) Testing 50-character Limit`I do get the release definition back, but I need to be able to get a release definition with a > 50-character name *and* use exact name matching.

Thanks for any help you can provide on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5558e13e-ea03-f735-02fc-3a7cfc0e3439
* Version Independent ID: 476675ed-e670-3938-f5b7-e7d43962a2e0
* Content: [Definitions (VSTS Release)](https://docs.microsoft.com/en-us/rest/api/vsts/release/definitions?view=vsts-rest-4.1)
* Content Source: [docs-ref-autogen/4.1/release/Definitions.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/release/Definitions.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by wnjenkin** [comment]
@brianpcurran this issue has been resolved

**Comment by brianpcurran** [comment]
👍 Thanks!

**Comment by clydeyeung** [comment]
Hi,

I am having the same problem and i see it says it is resolved. What's the solution?

Thanks.

Clyde
